// Move flags

"use strict";

import { toId } from "../utils/id";
import { LAST_GEN } from "./initializers";

/**
 * Move flag
 */
export type MoveFlag = "protect" | "mirror" | "heal" | "snatch" | "bullet" | "contact" | "nosleeptalk" | "failinstruct" | "bite" | "wind" | "nonsky" | "punch" | "reflectable" | "failmefirst" | "noassist" | "failcopycat" | "slicing" | "charge" | "authentic" | "distance" | "noparentalbond" | "gravity" | "sound" | "bypasssub" | "recharge" | "failencore" | "failmimic" | "allyanim" | "dance" | "powder" | "defrost" | "futuremove" | "mustpressure" | "pulse" | "pledgecombo" | "cantusetwice";

/**
 * Get move flags
 * @param gen The generation
 * @param move The move name
 * @returns The flags, as a set
 */
export function getMoveFlags(gen: number, move: string): Set<MoveFlag> {
    if (gen < 1 || gen > LAST_GEN) {
        return new Set();
    }

    move = toId(move);

    let flags: Set<MoveFlag> = new Set();

    for (let g = 1; g <= gen; g++) {
        const flagsData = FLAGS_DATA.get(g);

        if (!flagsData || !flagsData.has(move)) {
            continue;
        }

        flags = flagsData.get(move);
    }

    return flags;
}

const FLAGS_DATA: Map<number, Map<string, Set<MoveFlag>>> = new Map([
    [1, new Map([
        ["absorb", new Set(["protect", "mirror", "heal"])],
        ["acid", new Set(["protect", "mirror"])],
        ["acidarmor", new Set(["snatch"])],
        ["agility", new Set(["snatch"])],
        ["amnesia", new Set(["snatch"])],
        ["aurorabeam", new Set(["protect", "mirror"])],
        ["barrage", new Set(["bullet", "protect", "mirror"])],
        ["barrier", new Set(["snatch"])],
        ["bide", new Set(["contact", "protect", "nosleeptalk", "failinstruct"])],
        ["bind", new Set(["contact", "protect", "mirror"])],
        ["bite", new Set(["bite", "contact", "protect", "mirror"])],
        ["blizzard", new Set(["protect", "mirror", "wind"])],
        ["bodyslam", new Set(["contact", "protect", "mirror", "nonsky"])],
        ["boneclub", new Set(["protect", "mirror"])],
        ["bonemerang", new Set(["protect", "mirror"])],
        ["bubble", new Set(["protect", "mirror"])],
        ["bubblebeam", new Set(["protect", "mirror"])],
        ["clamp", new Set(["contact", "protect", "mirror"])],
        ["cometpunch", new Set(["contact", "protect", "mirror", "punch"])],
        ["confuseray", new Set(["protect", "reflectable", "mirror"])],
        ["confusion", new Set(["protect", "mirror"])],
        ["constrict", new Set(["contact", "protect", "mirror"])],
        ["conversion", new Set([])],
        ["counter", new Set(["contact", "protect", "failmefirst", "noassist", "failcopycat"])],
        ["crabhammer", new Set(["contact", "protect", "mirror"])],
        ["cut", new Set(["contact", "protect", "mirror", "slicing"])],
        ["defensecurl", new Set(["snatch"])],
        ["dig", new Set(["contact", "charge", "protect", "mirror", "nonsky", "nosleeptalk", "noassist", "failinstruct"])],
        ["disable", new Set(["protect", "mirror", "authentic"])],
        ["dizzypunch", new Set(["contact", "protect", "mirror", "punch"])],
        ["doubleedge", new Set(["contact", "protect", "mirror"])],
        ["doublekick", new Set(["contact", "protect", "mirror"])],
        ["doubleslap", new Set(["contact", "protect", "mirror"])],
        ["doubleteam", new Set(["snatch"])],
        ["dragonrage", new Set(["protect", "mirror"])],
        ["dreameater", new Set(["protect", "mirror", "heal"])],
        ["drillpeck", new Set(["contact", "protect", "mirror", "distance"])],
        ["earthquake", new Set(["protect", "mirror", "nonsky"])],
        ["eggbomb", new Set(["bullet", "protect", "mirror"])],
        ["ember", new Set(["protect", "mirror"])],
        ["explosion", new Set(["protect", "mirror", "noparentalbond"])],
        ["fireblast", new Set(["protect", "mirror"])],
        ["firepunch", new Set(["contact", "protect", "mirror", "punch"])],
        ["firespin", new Set(["protect", "mirror"])],
        ["fissure", new Set(["protect", "mirror", "nonsky"])],
        ["flamethrower", new Set(["protect", "mirror"])],
        ["flash", new Set(["protect", "reflectable", "mirror"])],
        ["fly", new Set(["contact", "charge", "protect", "mirror", "gravity", "distance", "nosleeptalk", "noassist", "failinstruct"])],
        ["focusenergy", new Set(["snatch"])],
        ["furyattack", new Set(["contact", "protect", "mirror"])],
        ["furyswipes", new Set(["contact", "protect", "mirror"])],
        ["glare", new Set(["protect", "reflectable", "mirror"])],
        ["growl", new Set(["protect", "reflectable", "mirror", "sound"])],
        ["growth", new Set(["snatch"])],
        ["guillotine", new Set(["contact", "protect", "mirror"])],
        ["gust", new Set(["protect", "mirror", "distance", "wind"])],
        ["harden", new Set(["snatch"])],
        ["haze", new Set(["bypasssub"])],
        ["headbutt", new Set(["contact", "protect", "mirror"])],
        ["highjumpkick", new Set(["contact", "protect", "mirror", "gravity"])],
        ["hornattack", new Set(["contact", "protect", "mirror"])],
        ["horndrill", new Set(["contact", "protect", "mirror"])],
        ["hydropump", new Set(["protect", "mirror"])],
        ["hyperbeam", new Set(["recharge", "protect", "mirror"])],
        ["hyperfang", new Set(["bite", "contact", "protect", "mirror"])],
        ["hypnosis", new Set(["protect", "reflectable", "mirror"])],
        ["icebeam", new Set(["protect", "mirror"])],
        ["icepunch", new Set(["contact", "protect", "mirror", "punch"])],
        ["jumpkick", new Set(["contact", "protect", "mirror", "gravity"])],
        ["karatechop", new Set(["contact", "protect", "mirror"])],
        ["kinesis", new Set(["protect", "reflectable", "mirror"])],
        ["leechlife", new Set(["contact", "protect", "mirror", "heal"])],
        ["leechseed", new Set(["protect", "reflectable", "mirror"])],
        ["leer", new Set(["protect", "reflectable", "mirror"])],
        ["lick", new Set(["contact", "protect", "mirror"])],
        ["lightscreen", new Set([])],
        ["lovelykiss", new Set(["protect", "reflectable", "mirror"])],
        ["lowkick", new Set(["contact", "protect", "mirror"])],
        ["meditate", new Set(["snatch"])],
        ["megadrain", new Set(["protect", "mirror", "heal"])],
        ["megakick", new Set(["contact", "protect", "mirror"])],
        ["megapunch", new Set(["contact", "protect", "mirror", "punch"])],
        ["metronome", new Set(["failencore", "nosleeptalk", "noassist", "failcopycat", "failinstruct", "failmimic"])],
        ["mimic", new Set(["protect", "bypasssub", "allyanim", "failencore", "nosleeptalk", "noassist", "failcopycat", "failinstruct", "failmimic"])],
        ["minimize", new Set(["snatch"])],
        ["mirrormove", new Set(["failencore", "nosleeptalk", "noassist", "failcopycat", "failinstruct", "failmimic"])],
        ["mist", new Set(["snatch"])],
        ["nightshade", new Set(["protect", "mirror"])],
        ["payday", new Set(["protect", "mirror"])],
        ["peck", new Set(["contact", "protect", "mirror", "distance"])],
        ["petaldance", new Set(["contact", "protect", "mirror", "dance", "failinstruct"])],
        ["pinmissile", new Set(["protect", "mirror"])],
        ["poisongas", new Set(["protect", "reflectable", "mirror"])],
        ["poisonpowder", new Set(["powder", "protect", "reflectable", "mirror"])],
        ["poisonsting", new Set(["protect", "mirror"])],
        ["pound", new Set(["contact", "protect", "mirror"])],
        ["psybeam", new Set(["protect", "mirror"])],
        ["psychic", new Set(["protect", "mirror"])],
        ["psywave", new Set(["protect", "mirror"])],
        ["quickattack", new Set(["contact", "protect", "mirror"])],
        ["rage", new Set(["contact", "protect", "mirror"])],
        ["razorleaf", new Set(["protect", "mirror", "slicing"])],
        ["razorwind", new Set(["charge", "protect", "mirror", "nosleeptalk", "failinstruct"])],
        ["recover", new Set(["snatch", "heal"])],
        ["reflect", new Set([])],
        ["rest", new Set(["snatch", "heal"])],
        ["roar", new Set(["protect", "mirror", "sound", "authentic"])],
        ["rockslide", new Set(["protect", "mirror"])],
        ["rockthrow", new Set(["protect", "mirror"])],
        ["rollingkick", new Set(["contact", "protect", "mirror"])],
        ["sandattack", new Set(["protect", "reflectable", "mirror"])],
        ["scratch", new Set(["contact", "protect", "mirror"])],
        ["screech", new Set(["protect", "reflectable", "mirror", "sound"])],
        ["seismictoss", new Set(["contact", "protect", "mirror", "nonsky"])],
        ["selfdestruct", new Set(["protect", "mirror", "noparentalbond"])],
        ["sharpen", new Set(["snatch"])],
        ["sing", new Set(["protect", "reflectable", "mirror", "sound"])],
        ["skullbash", new Set(["contact", "charge", "protect", "mirror", "nosleeptalk", "failinstruct"])],
        ["skyattack", new Set(["charge", "protect", "mirror", "distance", "nosleeptalk", "failinstruct"])],
        ["slam", new Set(["contact", "protect", "mirror", "nonsky"])],
        ["slash", new Set(["contact", "protect", "mirror", "slicing"])],
        ["sleeppowder", new Set(["powder", "protect", "reflectable", "mirror"])],
        ["sludge", new Set(["protect", "mirror"])],
        ["smog", new Set(["protect", "mirror"])],
        ["smokescreen", new Set(["protect", "reflectable", "mirror"])],
        ["softboiled", new Set(["snatch", "heal"])],
        ["solarbeam", new Set(["charge", "protect", "mirror", "nosleeptalk", "failinstruct"])],
        ["sonicboom", new Set(["protect", "mirror"])],
        ["spikecannon", new Set(["protect", "mirror"])],
        ["splash", new Set(["gravity"])],
        ["spore", new Set(["powder", "protect", "reflectable", "mirror"])],
        ["stomp", new Set(["contact", "protect", "mirror", "nonsky"])],
        ["strength", new Set(["contact", "protect", "mirror"])],
        ["stringshot", new Set(["protect", "reflectable", "mirror"])],
        ["struggle", new Set(["contact", "protect", "failencore", "failmefirst", "nosleeptalk", "noassist", "failcopycat", "failinstruct", "failmimic"])],
        ["stunspore", new Set(["powder", "protect", "reflectable", "mirror"])],
        ["submission", new Set(["contact", "protect", "mirror"])],
        ["substitute", new Set([])],
        ["superfang", new Set(["contact", "protect", "mirror"])],
        ["supersonic", new Set(["protect", "reflectable", "mirror", "sound"])],
        ["surf", new Set(["protect", "mirror", "nonsky"])],
        ["swift", new Set(["protect", "mirror"])],
        ["swordsdance", new Set(["snatch", "dance"])],
        ["tackle", new Set(["contact", "protect", "mirror"])],
        ["tailwhip", new Set(["protect", "reflectable", "mirror"])],
        ["takedown", new Set(["contact", "protect", "mirror"])],
        ["teleport", new Set([])],
        ["thrash", new Set(["contact", "protect", "mirror", "failinstruct"])],
        ["thunder", new Set(["protect", "mirror"])],
        ["thunderbolt", new Set(["protect", "mirror"])],
        ["thunderpunch", new Set(["contact", "protect", "mirror", "punch"])],
        ["thundershock", new Set(["protect", "mirror"])],
        ["thunderwave", new Set(["protect", "reflectable", "mirror"])],
        ["toxic", new Set(["protect", "reflectable", "mirror"])],
        ["transform", new Set(["authentic"])],
        ["triattack", new Set(["protect", "mirror"])],
        ["twineedle", new Set(["protect", "mirror"])],
        ["vinewhip", new Set(["contact", "protect", "mirror"])],
        ["visegrip", new Set(["contact", "protect", "mirror"])],
        ["waterfall", new Set(["contact", "protect", "mirror"])],
        ["watergun", new Set(["protect", "mirror"])],
        ["whirlwind", new Set(["protect", "mirror", "authentic"])],
        ["wingattack", new Set(["contact", "protect", "mirror", "distance"])],
        ["withdraw", new Set(["snatch"])],
        ["wrap", new Set(["contact", "protect", "mirror"])],
    ])],
    [2, new Map([
        ["aeroblast", new Set(["protect", "mirror", "distance"])],
        ["ancientpower", new Set(["contact", "protect", "mirror"])],
        ["attract", new Set(["protect", "reflectable", "mirror", "bypasssub"])],
        ["batonpass", new Set([])],
        ["beatup", new Set(["protect", "mirror", "allyanim"])],
        ["bellydrum", new Set(["snatch"])],
        ["bonerush", new Set(["protect", "mirror"])],
        ["charm", new Set(["protect", "reflectable", "mirror", "allyanim"])],
        ["conversion2", new Set(["bypasssub"])],
        ["cottonspore", new Set(["powder", "protect", "reflectable", "mirror"])],
        ["crosschop", new Set(["contact", "protect", "mirror"])],
        ["crunch", new Set(["bite", "contact", "protect", "mirror"])],
        ["curse", new Set(["bypasssub"])],
        ["destinybond", new Set(["bypasssub", "noassist", "failcopycat"])],
        ["detect", new Set(["noassist", "failcopycat"])],
        ["dragonbreath", new Set(["protect", "mirror"])],
        ["dynamicpunch", new Set(["contact", "protect", "mirror", "punch"])],
        ["encore", new Set(["protect", "mirror", "authentic"])],
        ["endure", new Set(["noassist", "failcopycat"])],
        ["extremespeed", new Set(["contact", "protect", "mirror"])],
        ["falseswipe", new Set(["contact", "protect", "mirror"])],
        ["feintattack", new Set(["protect", "mirror"])],
        ["flail", new Set(["contact", "protect", "mirror"])],
        ["flamewheel", new Set(["contact", "protect", "mirror", "defrost"])],
        ["foresight", new Set(["protect", "mirror", "authentic"])],
        ["frustration", new Set(["contact", "protect", "mirror"])],
        ["furycutter", new Set(["contact", "protect", "mirror", "slicing"])],
        ["futuresight", new Set(["allyanim", "futuremove"])],
        ["gigadrain", new Set(["protect", "mirror", "heal"])],
        ["healbell", new Set(["protect", "mirror", "sound"])],
        ["hiddenpower", new Set(["protect", "mirror"])],
        ["hiddenpowerbug", new Set(["protect", "mirror"])],
        ["hiddenpowerdark", new Set(["protect", "mirror"])],
        ["hiddenpowerdragon", new Set(["protect", "mirror"])],
        ["hiddenpowerelectric", new Set(["protect", "mirror"])],
        ["hiddenpowerfighting", new Set(["protect", "mirror"])],
        ["hiddenpowerfire", new Set(["protect", "mirror"])],
        ["hiddenpowerflying", new Set(["protect", "mirror"])],
        ["hiddenpowerghost", new Set(["protect", "mirror"])],
        ["hiddenpowergrass", new Set(["protect", "mirror"])],
        ["hiddenpowerground", new Set(["protect", "mirror"])],
        ["hiddenpowerice", new Set(["protect", "mirror"])],
        ["hiddenpowerpoison", new Set(["protect", "mirror"])],
        ["hiddenpowerpsychic", new Set(["protect", "mirror"])],
        ["hiddenpowerrock", new Set(["protect", "mirror"])],
        ["hiddenpowersteel", new Set(["protect", "mirror"])],
        ["hiddenpowerwater", new Set(["protect", "mirror"])],
        ["icywind", new Set(["protect", "mirror", "wind"])],
        ["irontail", new Set(["contact", "protect", "mirror"])],
        ["lightscreen", new Set(["snatch"])],
        ["lockon", new Set(["protect", "mirror"])],
        ["machpunch", new Set(["contact", "protect", "mirror", "punch"])],
        ["magnitude", new Set(["protect", "mirror", "nonsky"])],
        ["meanlook", new Set(["protect", "reflectable", "mirror"])],
        ["megahorn", new Set(["contact", "protect", "mirror"])],
        ["metalclaw", new Set(["contact", "protect", "mirror"])],
        ["milkdrink", new Set(["snatch", "heal"])],
        ["mindreader", new Set(["protect", "mirror"])],
        ["mirrorcoat", new Set(["protect", "failmefirst", "noassist"])],
        ["moonlight", new Set(["snatch", "heal"])],
        ["morningsun", new Set(["snatch", "heal"])],
        ["mudslap", new Set(["protect", "mirror"])],
        ["nightmare", new Set(["protect", "mirror"])],
        ["octazooka", new Set(["bullet", "protect", "mirror"])],
        ["outrage", new Set(["contact", "protect", "mirror", "failinstruct"])],
        ["painsplit", new Set(["protect", "mirror", "allyanim"])],
        ["perishsong", new Set(["sound", "distance"])],
        ["powdersnow", new Set(["protect", "mirror"])],
        ["present", new Set(["protect", "mirror"])],
        ["protect", new Set(["noassist", "failcopycat"])],
        ["psychup", new Set(["snatch", "authentic"])],
        ["pursuit", new Set(["contact", "protect", "mirror"])],
        ["raindance", new Set([])],
        ["rapidspin", new Set(["contact", "protect", "mirror"])],
        ["reflect", new Set(["snatch"])],
        ["return", new Set(["contact", "protect", "mirror"])],
        ["reversal", new Set(["contact", "protect", "mirror"])],
        ["rocksmash", new Set(["contact", "protect", "mirror"])],
        ["rollout", new Set(["contact", "protect", "mirror", "noparentalbond", "failinstruct"])],
        ["sacredfire", new Set(["protect", "mirror", "defrost"])],
        ["safeguard", new Set(["snatch"])],
        ["sandstorm", new Set(["wind"])],
        ["scaryface", new Set(["protect", "reflectable", "mirror", "allyanim"])],
        ["shadowball", new Set(["bullet", "protect", "mirror"])],
        ["sketch", new Set(["bypasssub", "allyanim", "failencore", "nosleeptalk", "noassist", "failcopycat", "failinstruct", "failmimic"])],
        ["sleeptalk", new Set(["failencore", "nosleeptalk", "noassist", "failcopycat", "failinstruct", "failmimic"])],
        ["sludgebomb", new Set(["bullet", "protect", "mirror"])],
        ["snore", new Set(["protect", "mirror", "sound"])],
        ["spark", new Set(["contact", "protect", "mirror"])],
        ["spiderweb", new Set(["protect", "reflectable", "mirror"])],
        ["spikes", new Set([])],
        ["spite", new Set(["protect", "mirror", "authentic"])],
        ["steelwing", new Set(["contact", "protect", "mirror"])],
        ["substitute", new Set(["snatch", "nonsky"])],
        ["sunnyday", new Set([])],
        ["swagger", new Set(["protect", "reflectable", "mirror", "allyanim"])],
        ["sweetkiss", new Set(["protect", "reflectable", "mirror"])],
        ["sweetscent", new Set(["protect", "reflectable", "mirror"])],
        ["synthesis", new Set(["snatch", "heal"])],
        ["thief", new Set(["contact", "protect", "mirror", "failmefirst", "noassist", "failcopycat"])],
        ["triplekick", new Set(["contact", "protect", "mirror"])],
        ["twister", new Set(["protect", "mirror", "wind"])],
        ["vitalthrow", new Set(["contact", "protect", "mirror"])],
        ["whirlpool", new Set(["protect", "mirror"])],
        ["zapcannon", new Set(["bullet", "protect", "mirror"])],
    ])],
    [3, new Map([
        ["aerialace", new Set(["contact", "protect", "mirror", "distance", "slicing"])],
        ["aircutter", new Set(["protect", "mirror", "slicing", "wind"])],
        ["armthrust", new Set(["contact", "protect", "mirror"])],
        ["aromatherapy", new Set(["snatch", "distance"])],
        ["assist", new Set(["failencore", "nosleeptalk", "noassist", "failcopycat", "failinstruct", "failmimic"])],
        ["astonish", new Set(["contact", "protect", "mirror"])],
        ["blastburn", new Set(["recharge", "protect", "mirror"])],
        ["blazekick", new Set(["contact", "protect", "mirror"])],
        ["block", new Set(["protect", "reflectable", "mirror"])],
        ["bounce", new Set(["contact", "charge", "protect", "mirror", "gravity", "distance", "nosleeptalk", "noassist", "failinstruct"])],
        ["brickbreak", new Set(["contact", "protect", "mirror"])],
        ["bulkup", new Set(["snatch"])],
        ["bulletseed", new Set(["bullet", "protect", "mirror"])],
        ["calmmind", new Set(["snatch"])],
        ["camouflage", new Set(["snatch"])],
        ["charge", new Set(["snatch"])],
        ["cosmicpower", new Set(["snatch"])],
        ["covet", new Set(["protect", "mirror"])],
        ["crushclaw", new Set(["contact", "protect", "mirror"])],
        ["dive", new Set(["contact", "charge", "protect", "mirror", "nonsky", "allyanim", "nosleeptalk", "noassist", "failinstruct"])],
        ["doomdesire", new Set(["futuremove"])],
        ["dragonclaw", new Set(["contact", "protect", "mirror"])],
        ["dragondance", new Set(["snatch", "dance"])],
        ["endeavor", new Set(["contact", "protect", "mirror", "noparentalbond"])],
        ["eruption", new Set(["protect", "mirror"])],
        ["extrasensory", new Set(["protect", "mirror"])],
        ["facade", new Set(["contact", "protect", "mirror"])],
        ["fakeout", new Set(["protect", "mirror"])],
        ["faketears", new Set(["protect", "reflectable", "mirror", "allyanim"])],
        ["featherdance", new Set(["protect", "reflectable", "mirror", "allyanim", "dance"])],
        ["flatter", new Set(["protect", "reflectable", "mirror", "allyanim"])],
        ["focuspunch", new Set(["contact", "protect", "punch", "failmefirst", "nosleeptalk", "noassist", "failcopycat", "failinstruct"])],
        ["followme", new Set(["noassist", "failcopycat"])],
        ["frenzyplant", new Set(["recharge", "protect", "mirror", "nonsky"])],
        ["grasswhistle", new Set(["protect", "reflectable", "mirror", "sound"])],
        ["grudge", new Set(["bypasssub"])],
        ["hail", new Set([])],
        ["heatwave", new Set(["protect", "mirror", "wind"])],
        ["helpinghand", new Set(["bypasssub", "noassist", "failcopycat"])],
        ["howl", new Set(["snatch"])],
        ["hydrocannon", new Set(["recharge", "protect", "mirror"])],
        ["hypervoice", new Set(["protect", "mirror", "sound"])],
        ["iceball", new Set(["bullet", "contact", "protect", "mirror", "noparentalbond", "failinstruct"])],
        ["iciclespear", new Set(["protect", "mirror"])],
        ["imprison", new Set(["authentic"])],
        ["ingrain", new Set(["snatch", "nonsky"])],
        ["irondefense", new Set(["snatch"])],
        ["knockoff", new Set(["contact", "protect", "mirror"])],
        ["leafblade", new Set(["contact", "protect", "mirror", "slicing"])],
        ["lusterpurge", new Set(["protect", "mirror"])],
        ["magicalleaf", new Set(["protect", "mirror"])],
        ["magiccoat", new Set([])],
        ["memento", new Set(["protect", "mirror"])],
        ["metalsound", new Set(["protect", "reflectable", "mirror", "sound"])],
        ["meteormash", new Set(["contact", "protect", "mirror", "punch"])],
        ["mistball", new Set(["bullet", "protect", "mirror"])],
        ["mudshot", new Set(["protect", "mirror"])],
        ["mudsport", new Set([])],
        ["muddywater", new Set(["protect", "mirror", "nonsky"])],
        ["naturepower", new Set(["failencore", "nosleeptalk", "noassist", "failcopycat", "failinstruct", "failmimic"])],
        ["needlearm", new Set(["contact", "protect", "mirror"])],
        ["odorsleuth", new Set(["protect", "mirror", "authentic"])],
        ["overheat", new Set(["contact", "protect", "mirror"])],
        ["poisonfang", new Set(["bite", "contact", "protect", "mirror"])],
        ["poisontail", new Set(["contact", "protect", "mirror"])],
        ["psychoboost", new Set(["protect", "mirror"])],
        ["recycle", new Set([])],
        ["refresh", new Set(["snatch"])],
        ["revenge", new Set(["contact", "protect", "mirror"])],
        ["rockblast", new Set(["bullet", "protect", "mirror"])],
        ["rocktomb", new Set(["protect", "mirror"])],
        ["roleplay", new Set(["bypasssub", "allyanim"])],
        ["sandtomb", new Set(["protect", "mirror"])],
        ["secretpower", new Set(["protect", "mirror"])],
        ["shadowpunch", new Set(["contact", "protect", "mirror", "punch"])],
        ["sheercold", new Set(["protect", "mirror"])],
        ["shockwave", new Set(["protect", "mirror"])],
        ["signalbeam", new Set(["protect", "mirror"])],
        ["silverwind", new Set(["protect", "mirror"])],
        ["skillswap", new Set(["protect", "mirror", "bypasssub", "allyanim"])],
        ["skyuppercut", new Set(["contact", "protect", "mirror", "punch"])],
        ["slackoff", new Set(["snatch", "heal"])],
        ["smellingsalts", new Set(["contact", "protect", "mirror"])],
        ["snatch", new Set(["bypasssub", "mustpressure", "noassist", "failcopycat"])],
        ["spitup", new Set(["protect"])],
        ["stockpile", new Set(["snatch"])],
        ["superpower", new Set(["contact", "protect", "mirror"])],
        ["swallow", new Set(["snatch", "heal"])],
        ["tailglow", new Set(["snatch"])],
        ["taunt", new Set(["protect", "mirror", "authentic"])],
        ["teeterdance", new Set(["protect", "mirror", "dance"])],
        ["tickle", new Set(["protect", "reflectable", "mirror", "authentic"])],
        ["torment", new Set(["protect", "mirror", "authentic"])],
        ["trick", new Set(["protect", "mirror", "allyanim", "noassist", "failcopycat"])],
        ["uproar", new Set(["protect", "mirror", "sound"])],
        ["volttackle", new Set(["contact", "protect", "mirror"])],
        ["waterpulse", new Set(["protect", "pulse", "mirror", "distance"])],
        ["watersport", new Set([])],
        ["waterspout", new Set(["protect", "mirror"])],
        ["weatherball", new Set(["bullet", "protect", "mirror"])],
        ["willowisp", new Set(["protect", "reflectable", "mirror"])],
        ["wish", new Set(["heal"])],
        ["yawn", new Set(["protect", "reflectable", "mirror"])],
    ])],
    [4, new Map([
        ["acupressure", new Set(["snatch"])],
        ["airslash", new Set(["protect", "mirror", "distance", "slicing"])],
        ["ancientpower", new Set(["protect", "mirror"])],
        ["aquajet", new Set(["contact", "protect", "mirror"])],
        ["aquaring", new Set([])],
        ["aquatail", new Set(["contact", "protect", "mirror"])],
        ["assurance", new Set(["contact", "protect", "mirror"])],
        ["attackorder", new Set(["protect", "mirror"])],
        ["aurasphere", new Set(["bullet", "protect", "pulse", "mirror", "distance"])],
        ["avalanche", new Set(["contact", "protect", "mirror"])],
        ["bravebird", new Set(["contact", "protect", "mirror", "distance"])],
        ["brine", new Set(["protect", "mirror"])],
        ["bugbite", new Set(["contact", "protect", "mirror"])],
        ["bugbuzz", new Set(["protect", "mirror", "sound"])],
        ["bulletpunch", new Set(["contact", "protect", "mirror", "punch"])],
        ["captivate", new Set(["protect", "reflectable", "mirror"])],
        ["chargebeam", new Set(["protect", "mirror"])],
        ["chatter", new Set(["protect", "mirror", "sound", "distance"])],
        ["closecombat", new Set(["contact", "protect", "mirror"])],
        ["copycat", new Set(["failencore", "nosleeptalk", "noassist", "failcopycat", "failinstruct", "failmimic"])],
        ["covet", new Set(["contact", "protect", "mirror", "failmefirst", "noassist", "failcopycat"])],
        ["crosspoison", new Set(["contact", "protect", "mirror", "slicing"])],
        ["crushgrip", new Set(["contact", "protect", "mirror"])],
        ["darkpulse", new Set(["protect", "pulse", "mirror", "distance"])],
        ["darkvoid", new Set(["protect", "reflectable", "mirror"])],
        ["defendorder", new Set(["snatch"])],
        ["defog", new Set(["protect", "mirror", "authentic"])],
        ["discharge", new Set(["protect", "mirror"])],
        ["doublehit", new Set(["contact", "protect", "mirror"])],
        ["dracometeor", new Set(["protect", "mirror"])],
        ["dragonpulse", new Set(["protect", "pulse", "mirror", "distance"])],
        ["dragonrush", new Set(["contact", "protect", "mirror"])],
        ["drainpunch", new Set(["contact", "protect", "mirror", "punch", "heal"])],
        ["earthpower", new Set(["protect", "mirror", "nonsky"])],
        ["embargo", new Set(["protect", "mirror"])],
        ["energyball", new Set(["bullet", "protect", "mirror"])],
        ["fakeout", new Set(["contact", "protect", "mirror"])],
        ["feint", new Set(["mirror", "noassist", "failcopycat"])],
        ["feintattack", new Set(["contact", "protect", "mirror"])],
        ["firefang", new Set(["bite", "contact", "protect", "mirror"])],
        ["flareblitz", new Set(["contact", "protect", "mirror", "defrost"])],
        ["flashcannon", new Set(["protect", "mirror"])],
        ["fling", new Set(["protect", "mirror", "allyanim", "noparentalbond"])],
        ["focusblast", new Set(["bullet", "protect", "mirror"])],
        ["forcepalm", new Set(["contact", "protect", "mirror"])],
        ["gastroacid", new Set(["protect", "reflectable", "mirror", "allyanim"])],
        ["gigaimpact", new Set(["contact", "recharge", "protect", "mirror"])],
        ["grassknot", new Set(["contact", "protect", "mirror", "nonsky"])],
        ["gravity", new Set(["nonsky"])],
        ["guardswap", new Set(["protect", "mirror", "bypasssub", "allyanim"])],
        ["gunkshot", new Set(["protect", "mirror"])],
        ["gyroball", new Set(["bullet", "contact", "protect", "mirror"])],
        ["hammerarm", new Set(["contact", "protect", "mirror", "punch"])],
        ["headsmash", new Set(["contact", "protect", "mirror"])],
        ["healblock", new Set(["protect", "mirror"])],
        ["healingwish", new Set(["heal"])],
        ["healorder", new Set(["snatch", "heal"])],
        ["heartswap", new Set(["protect", "mirror", "bypasssub", "allyanim"])],
        ["icefang", new Set(["bite", "contact", "protect", "mirror"])],
        ["iceshard", new Set(["protect", "mirror"])],
        ["ironhead", new Set(["contact", "protect", "mirror"])],
        ["judgment", new Set(["protect", "mirror"])],
        ["lastresort", new Set(["contact", "protect", "mirror"])],
        ["lavaplume", new Set(["protect", "mirror"])],
        ["leafstorm", new Set(["protect", "mirror"])],
        ["luckychant", new Set([])],
        ["lunardance", new Set(["heal"])],
        ["magmastorm", new Set(["protect", "mirror"])],
        ["magnetbomb", new Set(["bullet", "protect", "mirror"])],
        ["magnetrise", new Set(["gravity"])],
        ["mefirst", new Set(["protect", "bypasssub", "failencore", "failmefirst", "nosleeptalk", "noassist", "failcopycat", "failinstruct", "failmimic"])],
        ["metalburst", new Set(["protect", "mirror", "failmefirst"])],
        ["miracleeye", new Set(["protect", "mirror", "authentic"])],
        ["mirrorshot", new Set(["protect", "mirror"])],
        ["mudbomb", new Set(["bullet", "protect", "mirror"])],
        ["nastyplot", new Set(["snatch"])],
        ["naturalgift", new Set(["protect", "mirror"])],
        ["nightslash", new Set(["contact", "protect", "mirror", "slicing"])],
        ["ominouswind", new Set(["protect", "mirror"])],
        ["overheat", new Set(["protect", "mirror"])],
        ["payback", new Set(["contact", "protect", "mirror"])],
        ["pluck", new Set(["contact", "protect", "mirror", "distance"])],
        ["poisonjab", new Set(["contact", "protect", "mirror"])],
        ["powergem", new Set(["protect", "mirror"])],
        ["powerswap", new Set(["protect", "mirror", "bypasssub", "allyanim"])],
        ["powertrick", new Set([])],
        ["powerwhip", new Set(["contact", "protect", "mirror"])],
        ["psychocut", new Set(["protect", "mirror", "slicing"])],
        ["psychoshift", new Set(["protect", "mirror"])],
        ["punishment", new Set(["contact", "protect", "mirror"])],
        ["roaroftime", new Set(["recharge", "protect", "mirror"])],
        ["rockclimb", new Set(["contact", "protect", "mirror"])],
        ["rockpolish", new Set(["snatch"])],
        ["rockwrecker", new Set(["bullet", "recharge", "protect", "mirror"])],
        ["roost", new Set(["snatch", "heal"])],
        ["seedbomb", new Set(["bullet", "protect", "mirror"])],
        ["seedflare", new Set(["protect", "mirror"])],
        ["shadowclaw", new Set(["contact", "protect", "mirror"])],
        ["shadowforce", new Set(["contact", "charge", "mirror", "nosleeptalk", "noassist", "failinstruct"])],
        ["shadowsneak", new Set(["contact", "protect", "mirror"])],
        ["spacialrend", new Set(["protect", "mirror"])],
        ["stealthrock", new Set([])],
        ["stoneedge", new Set(["protect", "mirror"])],
        ["suckerpunch", new Set(["contact", "protect", "mirror"])],
        ["switcheroo", new Set(["protect", "mirror", "allyanim", "noassist", "failcopycat"])],
        ["tailwind", new Set(["snatch", "wind"])],
        ["thunderfang", new Set(["bite", "contact", "protect", "mirror"])],
        ["tickle", new Set(["protect", "reflectable", "mirror", "allyanim"])],
        ["toxicspikes", new Set([])],
        ["trickroom", new Set(["mirror"])],
        ["trumpcard", new Set(["contact", "protect", "mirror"])],
        ["uturn", new Set(["contact", "protect", "mirror"])],
        ["vacuumwave", new Set(["protect", "mirror"])],
        ["wakeupslap", new Set(["contact", "protect", "mirror"])],
        ["woodhammer", new Set(["contact", "protect", "mirror"])],
        ["worryseed", new Set(["protect", "reflectable", "mirror", "allyanim"])],
        ["wringout", new Set(["contact", "protect", "mirror"])],
        ["xscissor", new Set(["contact", "protect", "mirror", "slicing"])],
        ["zenheadbutt", new Set(["contact", "protect", "mirror"])],
    ])],
    [5, new Map([
        ["acidspray", new Set(["bullet", "protect", "mirror"])],
        ["acrobatics", new Set(["contact", "protect", "mirror", "distance"])],
        ["acupressure", new Set([])],
        ["afteryou", new Set(["bypasssub", "allyanim"])],
        ["allyswitch", new Set([])],
        ["aquaring", new Set(["snatch"])],
        ["autotomize", new Set(["snatch"])],
        ["bestow", new Set(["protect", "mirror"])],
        ["blueflare", new Set(["protect", "mirror"])],
        ["boltstrike", new Set(["contact", "protect", "mirror"])],
        ["bulldoze", new Set(["protect", "mirror", "nonsky"])],
        ["chipaway", new Set(["contact", "protect", "mirror"])],
        ["circlethrow", new Set(["contact", "protect", "mirror", "noassist", "failcopycat"])],
        ["clearsmog", new Set(["protect", "mirror"])],
        ["coil", new Set(["snatch"])],
        ["conversion", new Set(["snatch"])],
        ["cottonguard", new Set(["snatch"])],
        ["defog", new Set(["protect", "reflectable", "mirror", "bypasssub"])],
        ["disable", new Set(["protect", "reflectable", "mirror", "bypasssub"])],
        ["dragontail", new Set(["contact", "protect", "mirror", "noassist", "failcopycat"])],
        ["drillrun", new Set(["contact", "protect", "mirror"])],
        ["dualchop", new Set(["contact", "protect", "mirror"])],
        ["echoedvoice", new Set(["protect", "mirror", "sound"])],
        ["electroball", new Set(["bullet", "protect", "mirror"])],
        ["electroweb", new Set(["protect", "mirror"])],
        ["embargo", new Set(["protect", "reflectable", "mirror"])],
        ["encore", new Set(["protect", "reflectable", "mirror", "bypasssub", "failencore"])],
        ["entrainment", new Set(["protect", "reflectable", "mirror", "allyanim"])],
        ["fierydance", new Set(["protect", "mirror", "dance"])],
        ["finalgambit", new Set(["contact", "protect"])],
        ["firepledge", new Set(["protect", "mirror", "nonsky", "pledgecombo"])],
        ["flameburst", new Set(["protect", "mirror"])],
        ["flamecharge", new Set(["contact", "protect", "mirror"])],
        ["foresight", new Set(["protect", "reflectable", "mirror", "bypasssub"])],
        ["foulplay", new Set(["contact", "protect", "mirror"])],
        ["freezeshock", new Set(["charge", "protect", "mirror", "nosleeptalk", "failinstruct"])],
        ["frostbreath", new Set(["protect", "mirror"])],
        ["fusionbolt", new Set(["protect", "mirror"])],
        ["fusionflare", new Set(["protect", "mirror", "defrost"])],
        ["geargrind", new Set(["contact", "protect", "mirror"])],
        ["glaciate", new Set(["protect", "mirror"])],
        ["grasspledge", new Set(["protect", "mirror", "nonsky", "pledgecombo"])],
        ["guardsplit", new Set(["protect", "allyanim"])],
        ["headcharge", new Set(["contact", "protect", "mirror"])],
        ["healblock", new Set(["protect", "reflectable", "mirror"])],
        ["healingwish", new Set(["snatch", "heal"])],
        ["healpulse", new Set(["protect", "pulse", "reflectable", "distance", "heal", "allyanim"])],
        ["heartstamp", new Set(["contact", "protect", "mirror"])],
        ["heatcrash", new Set(["contact", "protect", "mirror", "nonsky"])],
        ["heavyslam", new Set(["contact", "protect", "mirror", "nonsky"])],
        ["hex", new Set(["protect", "mirror"])],
        ["honeclaws", new Set(["snatch"])],
        ["hornleech", new Set(["contact", "protect", "mirror", "heal"])],
        ["hurricane", new Set(["protect", "mirror", "distance", "wind"])],
        ["iceburn", new Set(["charge", "protect", "mirror", "nosleeptalk", "failinstruct"])],
        ["iciclecrash", new Set(["protect", "mirror"])],
        ["imprison", new Set(["snatch", "bypasssub", "mustpressure"])],
        ["incinerate", new Set(["protect", "mirror"])],
        ["inferno", new Set(["protect", "mirror"])],
        ["leaftornado", new Set(["protect", "mirror"])],
        ["lowsweep", new Set(["contact", "protect", "mirror"])],
        ["luckychant", new Set(["snatch"])],
        ["lunardance", new Set(["snatch", "heal", "dance"])],
        ["magicroom", new Set(["mirror"])],
        ["magnetrise", new Set(["snatch", "gravity"])],
        ["miracleeye", new Set(["protect", "reflectable", "mirror", "bypasssub"])],
        ["nightdaze", new Set(["protect", "mirror"])],
        ["odorsleuth", new Set(["protect", "reflectable", "mirror", "bypasssub", "allyanim"])],
        ["powersplit", new Set(["protect", "allyanim"])],
        ["powertrick", new Set(["snatch"])],
        ["psychup", new Set(["bypasssub", "allyanim"])],
        ["psyshock", new Set(["protect", "mirror"])],
        ["psystrike", new Set(["protect", "mirror"])],
        ["quash", new Set(["protect", "mirror"])],
        ["quickguard", new Set(["snatch"])],
        ["quiverdance", new Set(["snatch", "dance"])],
        ["ragepowder", new Set([])],
        ["razorshell", new Set(["contact", "protect", "mirror", "slicing"])],
        ["recycle", new Set(["snatch"])],
        ["reflecttype", new Set(["protect", "bypasssub", "allyanim"])],
        ["relicsong", new Set(["protect", "mirror", "sound"])],
        ["retaliate", new Set(["contact", "protect", "mirror"])],
        ["roar", new Set(["protect", "reflectable", "mirror", "sound", "authentic"])],
        ["round", new Set(["protect", "mirror", "sound"])],
        ["sacredsword", new Set(["contact", "protect", "mirror", "slicing"])],
        ["scald", new Set(["protect", "mirror", "defrost"])],
        ["searingshot", new Set(["bullet", "protect", "mirror"])],
        ["secretsword", new Set(["protect", "mirror"])],
        ["shellsmash", new Set(["snatch"])],
        ["shiftgear", new Set(["snatch"])],
        ["simplebeam", new Set(["protect", "reflectable", "mirror", "allyanim"])],
        ["skydrop", new Set(["contact", "charge", "protect", "mirror", "gravity", "distance", "nosleeptalk", "noassist", "failinstruct"])],
        ["sludgewave", new Set(["protect", "mirror"])],
        ["smackdown", new Set(["protect", "mirror", "nonsky"])],
        ["snarl", new Set(["protect", "mirror", "sound"])],
        ["soak", new Set(["protect", "reflectable", "mirror", "allyanim"])],
        ["spikes", new Set(["reflectable", "nonsky", "mustpressure"])],
        ["spite", new Set(["protect", "reflectable", "mirror", "bypasssub"])],
        ["stealthrock", new Set(["reflectable", "mustpressure"])],
        ["steamroller", new Set(["contact", "protect", "mirror"])],
        ["storedpower", new Set(["protect", "mirror"])],
        ["stormthrow", new Set(["contact", "protect", "mirror"])],
        ["strugglebug", new Set(["protect", "mirror"])],
        ["synchronoise", new Set(["protect", "mirror"])],
        ["tailslap", new Set(["contact", "protect", "mirror"])],
        ["taunt", new Set(["protect", "reflectable", "mirror", "bypasssub"])],
        ["technoblast", new Set(["protect", "mirror"])],
        ["telekinesis", new Set(["protect", "reflectable", "mirror", "gravity", "allyanim"])],
        ["torment", new Set(["protect", "reflectable", "mirror", "bypasssub"])],
        ["toxicspikes", new Set(["reflectable", "nonsky", "mustpressure"])],
        ["transform", new Set(["allyanim", "failencore", "noassist", "failcopycat", "failinstruct", "failmimic"])],
        ["vcreate", new Set(["contact", "protect", "mirror"])],
        ["venoshock", new Set(["protect", "mirror"])],
        ["voltswitch", new Set(["protect", "mirror"])],
        ["waterpledge", new Set(["protect", "mirror", "nonsky", "pledgecombo"])],
        ["whirlwind", new Set(["protect", "reflectable", "mirror", "authentic"])],
        ["wideguard", new Set(["snatch"])],
        ["wildcharge", new Set(["contact", "protect", "mirror"])],
        ["wish", new Set(["snatch", "heal"])],
        ["wonderroom", new Set(["mirror"])],
        ["workup", new Set(["snatch"])],
    ])],
    [6, new Map([
        ["aromaticmist", new Set(["bypasssub"])],
        ["babydolleyes", new Set(["protect", "reflectable", "mirror", "allyanim"])],
        ["belch", new Set(["protect", "failmefirst", "nosleeptalk", "noassist", "failcopycat", "failinstruct", "failmimic"])],
        ["bestow", new Set(["mirror", "bypasssub", "allyanim", "noassist", "failcopycat"])],
        ["block", new Set(["reflectable", "mirror"])],
        ["boomburst", new Set(["protect", "mirror", "sound", "bypasssub"])],
        ["bugbuzz", new Set(["protect", "mirror", "sound", "bypasssub"])],
        ["celebrate", new Set(["nosleeptalk", "noassist", "failcopycat", "failinstruct", "failmimic"])],
        ["chatter", new Set(["protect", "mirror", "sound", "distance", "bypasssub", "nosleeptalk", "noassist", "failcopycat", "failinstruct", "failmimic"])],
        ["confide", new Set(["reflectable", "mirror", "sound", "bypasssub"])],
        ["craftyshield", new Set([])],
        ["dazzlinggleam", new Set(["protect", "mirror"])],
        ["diamondstorm", new Set(["protect", "mirror"])],
        ["disarmingvoice", new Set(["protect", "mirror", "sound", "bypasssub"])],
        ["dragonascent", new Set(["contact", "protect", "mirror", "distance"])],
        ["drainingkiss", new Set(["contact", "protect", "mirror", "heal"])],
        ["echoedvoice", new Set(["protect", "mirror", "sound", "bypasssub"])],
        ["eerieimpulse", new Set(["protect", "reflectable", "mirror"])],
        ["electricterrain", new Set(["nonsky"])],
        ["electrify", new Set(["protect", "mirror", "allyanim"])],
        ["fairylock", new Set(["mirror", "bypasssub"])],
        ["fairywind", new Set(["protect", "mirror", "wind"])],
        ["fellstinger", new Set(["contact", "protect", "mirror"])],
        ["finalgambit", new Set(["protect", "noparentalbond"])],
        ["flowershield", new Set(["distance"])],
        ["flyingpress", new Set(["contact", "protect", "mirror", "gravity", "distance", "nonsky"])],
        ["forestscurse", new Set(["protect", "reflectable", "mirror", "allyanim"])],
        ["freezedry", new Set(["protect", "mirror"])],
        ["geomancy", new Set(["charge", "nonsky", "nosleeptalk", "failinstruct"])],
        ["grasswhistle", new Set(["protect", "reflectable", "mirror", "sound", "bypasssub"])],
        ["grassyterrain", new Set(["nonsky"])],
        ["growl", new Set(["protect", "reflectable", "mirror", "sound", "bypasssub"])],
        ["happyhour", new Set([])],
        ["healbell", new Set(["snatch", "sound", "distance", "bypasssub"])],
        ["holdback", new Set(["contact", "protect", "mirror"])],
        ["holdhands", new Set(["bypasssub", "nosleeptalk", "noassist", "failcopycat", "failinstruct", "failmimic"])],
        ["hyperspacefury", new Set(["mirror", "bypasssub"])],
        ["hyperspacehole", new Set(["mirror", "bypasssub"])],
        ["hypervoice", new Set(["protect", "mirror", "sound", "bypasssub"])],
        ["infestation", new Set(["contact", "protect", "mirror"])],
        ["iondeluge", new Set([])],
        ["kingsshield", new Set(["noassist", "failcopycat", "failinstruct"])],
        ["landswrath", new Set(["protect", "mirror", "nonsky"])],
        ["lightofruin", new Set(["protect", "mirror"])],
        ["magneticflux", new Set(["snatch", "distance", "bypasssub"])],
        ["matblock", new Set(["snatch", "nonsky", "noassist", "failcopycat"])],
        ["meanlook", new Set(["reflectable", "mirror"])],
        ["metalsound", new Set(["protect", "reflectable", "mirror", "sound", "bypasssub", "allyanim"])],
        ["mistyterrain", new Set(["nonsky"])],
        ["moonblast", new Set(["protect", "mirror"])],
        ["mudsport", new Set(["nonsky"])],
        ["mysticalfire", new Set(["protect", "mirror"])],
        ["nobleroar", new Set(["protect", "reflectable", "mirror", "sound", "bypasssub"])],
        ["nuzzle", new Set(["contact", "protect", "mirror"])],
        ["oblivionwing", new Set(["protect", "mirror", "distance", "heal"])],
        ["originpulse", new Set(["protect", "pulse", "mirror"])],
        ["paraboliccharge", new Set(["protect", "mirror", "heal"])],
        ["partingshot", new Set(["protect", "reflectable", "mirror", "sound", "bypasssub"])],
        ["perishsong", new Set(["sound", "distance", "bypasssub"])],
        ["petalblizzard", new Set(["protect", "mirror", "wind"])],
        ["phantomforce", new Set(["contact", "charge", "mirror", "nosleeptalk", "noassist", "failinstruct"])],
        ["playnice", new Set(["reflectable", "mirror", "bypasssub"])],
        ["playrough", new Set(["contact", "protect", "mirror"])],
        ["powder", new Set(["powder", "protect", "reflectable", "mirror", "bypasssub"])],
        ["poweruppunch", new Set(["contact", "protect", "mirror", "punch"])],
        ["precipiceblades", new Set(["protect", "mirror", "nonsky"])],
        ["ragepowder", new Set(["powder", "noassist", "failcopycat"])],
        ["relicsong", new Set(["protect", "mirror", "sound", "bypasssub"])],
        ["roar", new Set(["reflectable", "mirror", "sound", "bypasssub", "allyanim", "noassist", "failcopycat"])],
        ["rototiller", new Set(["distance", "nonsky"])],
        ["round", new Set(["protect", "mirror", "sound", "bypasssub"])],
        ["screech", new Set(["protect", "reflectable", "mirror", "sound", "bypasssub", "allyanim"])],
        ["sing", new Set(["protect", "reflectable", "mirror", "sound", "bypasssub"])],
        ["snarl", new Set(["protect", "mirror", "sound", "bypasssub"])],
        ["snore", new Set(["protect", "mirror", "sound", "bypasssub"])],
        ["spikyshield", new Set(["noassist", "failcopycat"])],
        ["steameruption", new Set(["protect", "mirror", "defrost"])],
        ["stickyweb", new Set(["reflectable"])],
        ["supersonic", new Set(["protect", "reflectable", "mirror", "sound", "bypasssub"])],
        ["thousandarrows", new Set(["protect", "mirror", "nonsky"])],
        ["thousandwaves", new Set(["protect", "mirror", "nonsky"])],
        ["topsyturvy", new Set(["protect", "reflectable", "mirror", "allyanim"])],
        ["trickortreat", new Set(["protect", "reflectable", "mirror", "allyanim"])],
        ["uproar", new Set(["protect", "mirror", "sound", "bypasssub", "nosleeptalk", "failinstruct"])],
        ["venomdrench", new Set(["protect", "reflectable", "mirror"])],
        ["watershuriken", new Set(["protect", "mirror"])],
        ["watersport", new Set(["nonsky"])],
        ["whirlwind", new Set(["reflectable", "mirror", "bypasssub", "allyanim", "wind", "noassist", "failcopycat"])],
    ])],
    [7, new Map([
        ["10000000voltthunderbolt", new Set([])],
        ["accelerock", new Set(["contact", "protect", "mirror"])],
        ["aciddownpour", new Set([])],
        ["alloutpummeling", new Set([])],
        ["anchorshot", new Set(["contact", "protect", "mirror"])],
        ["auroraveil", new Set(["snatch"])],
        ["baddybad", new Set(["protect", "mirror"])],
        ["banefulbunker", new Set(["noassist", "failcopycat"])],
        ["beakblast", new Set(["bullet", "protect", "noassist", "failmefirst", "nosleeptalk", "failcopycat", "failinstruct"])],
        ["blackholeeclipse", new Set([])],
        ["bloomdoom", new Set([])],
        ["bouncybubble", new Set(["protect", "mirror", "heal"])],
        ["breakneckblitz", new Set([])],
        ["brutalswing", new Set(["contact", "protect", "mirror"])],
        ["burnup", new Set(["protect", "mirror", "defrost"])],
        ["buzzybuzz", new Set(["protect", "mirror"])],
        ["catastropika", new Set(["contact"])],
        ["clangingscales", new Set(["protect", "mirror", "sound", "bypasssub"])],
        ["clangoroussoulblaze", new Set(["sound", "bypasssub"])],
        ["continentalcrush", new Set([])],
        ["coreenforcer", new Set(["protect", "mirror"])],
        ["corkscrewcrash", new Set([])],
        ["darkestlariat", new Set(["contact", "protect", "mirror"])],
        ["devastatingdrake", new Set([])],
        ["doubleironbash", new Set(["contact", "protect", "mirror", "punch"])],
        ["dragonhammer", new Set(["contact", "protect", "mirror"])],
        ["extremeevoboost", new Set([])],
        ["firelash", new Set(["contact", "protect", "mirror"])],
        ["firstimpression", new Set(["contact", "protect", "mirror"])],
        ["fleurcannon", new Set(["protect", "mirror"])],
        ["floatyfall", new Set(["contact", "protect", "mirror", "gravity"])],
        ["floralhealing", new Set(["protect", "reflectable", "heal", "allyanim"])],
        ["freezyfrost", new Set(["protect", "mirror"])],
        ["gearup", new Set(["snatch", "bypasssub"])],
        ["genesissupernova", new Set([])],
        ["gigavolthavoc", new Set([])],
        ["glitzyglow", new Set(["protect", "mirror"])],
        ["guardianofalola", new Set([])],
        ["highhorsepower", new Set(["contact", "protect", "mirror"])],
        ["hydrovortex", new Set([])],
        ["icehammer", new Set(["contact", "protect", "mirror", "punch"])],
        ["infernooverdrive", new Set([])],
        ["instruct", new Set(["protect", "bypasssub", "allyanim", "failinstruct"])],
        ["laserfocus", new Set(["snatch"])],
        ["leafage", new Set(["protect", "mirror"])],
        ["letssnuggleforever", new Set(["contact"])],
        ["lightthatburnsthesky", new Set([])],
        ["liquidation", new Set(["contact", "protect", "mirror"])],
        ["lunge", new Set(["contact", "protect", "mirror"])],
        ["maliciousmoonsault", new Set(["contact"])],
        ["menacingmoonrazemaelstrom", new Set([])],
        ["mindblown", new Set(["protect", "mirror"])],
        ["moongeistbeam", new Set(["protect", "mirror"])],
        ["multiattack", new Set(["contact", "protect", "mirror"])],
        ["naturesmadness", new Set(["protect", "mirror"])],
        ["neverendingnightmare", new Set([])],
        ["oceanicoperetta", new Set([])],
        ["photongeyser", new Set(["protect", "mirror"])],
        ["pikapapow", new Set(["protect", "mirror"])],
        ["plasmafists", new Set(["contact", "protect", "mirror", "punch"])],
        ["pollenpuff", new Set(["bullet", "protect", "mirror", "allyanim"])],
        ["powertrip", new Set(["contact", "protect", "mirror"])],
        ["prismaticlaser", new Set(["recharge", "protect", "mirror"])],
        ["psychicfangs", new Set(["bite", "contact", "protect", "mirror"])],
        ["psychicterrain", new Set(["nonsky"])],
        ["pulverizingpancake", new Set(["contact"])],
        ["purify", new Set(["protect", "reflectable", "heal"])],
        ["revelationdance", new Set(["protect", "mirror", "dance"])],
        ["sappyseed", new Set(["protect", "reflectable", "mirror"])],
        ["savagespinout", new Set([])],
        ["searingsunrazesmash", new Set(["contact"])],
        ["shadowbone", new Set(["protect", "mirror"])],
        ["shatteredpsyche", new Set([])],
        ["shelltrap", new Set(["protect", "failmefirst", "nosleeptalk", "noassist", "failcopycat", "failinstruct"])],
        ["shoreup", new Set(["snatch", "heal"])],
        ["sinisterarrowraid", new Set([])],
        ["sizzlyslide", new Set(["contact", "protect", "mirror", "defrost"])],
        ["smartstrike", new Set(["contact", "protect", "mirror"])],
        ["solarblade", new Set(["contact", "charge", "protect", "mirror", "slicing", "nosleeptalk", "failinstruct"])],
        ["soulstealing7starstrike", new Set(["contact"])],
        ["sparklingaria", new Set(["protect", "mirror", "sound", "bypasssub"])],
        ["sparklyswirl", new Set(["protect", "mirror"])],
        ["spectralthief", new Set(["contact", "protect", "mirror", "bypasssub"])],
        ["speedswap", new Set(["protect", "mirror", "bypasssub", "allyanim"])],
        ["spiritshackle", new Set(["protect", "mirror"])],
        ["splinteredstormshards", new Set([])],
        ["splishysplash", new Set(["protect", "mirror"])],
        ["spotlight", new Set(["protect", "reflectable", "allyanim", "noassist", "failcopycat"])],
        ["stokedsparksurfer", new Set([])],
        ["stompingtantrum", new Set(["contact", "protect", "mirror"])],
        ["strengthsap", new Set(["protect", "reflectable", "mirror", "heal"])],
        ["subzeroslammer", new Set([])],
        ["sunsteelstrike", new Set(["contact", "protect", "mirror"])],
        ["supersonicskystrike", new Set([])],
        ["tearfullook", new Set(["reflectable", "mirror"])],
        ["tectonicrage", new Set([])],
        ["throatchop", new Set(["contact", "protect", "mirror"])],
        ["toxicthread", new Set(["protect", "reflectable", "mirror"])],
        ["tropkick", new Set(["contact", "protect", "mirror"])],
        ["twinkletackle", new Set([])],
        ["veeveevolley", new Set(["contact", "protect", "mirror"])],
        ["zingzap", new Set(["contact", "protect", "mirror"])],
        ["zippyzap", new Set(["contact", "protect", "mirror"])],
    ])],
    [8, new Map([
        ["appleacid", new Set(["protect", "mirror"])],
        ["astralbarrage", new Set(["protect", "mirror"])],
        ["aurawheel", new Set(["protect", "mirror"])],
        ["behemothbash", new Set(["contact", "protect", "mirror", "failcopycat", "failmimic"])],
        ["behemothblade", new Set(["contact", "protect", "mirror", "slicing", "failcopycat", "failmimic"])],
        ["bodypress", new Set(["contact", "protect", "mirror"])],
        ["boltbeak", new Set(["contact", "protect", "mirror"])],
        ["branchpoke", new Set(["contact", "protect", "mirror"])],
        ["breakingswipe", new Set(["contact", "protect", "mirror"])],
        ["burningjealousy", new Set(["protect", "mirror"])],
        ["clangoroussoul", new Set(["snatch", "sound", "dance"])],
        ["coaching", new Set(["bypasssub", "allyanim"])],
        ["corrosivegas", new Set(["protect", "reflectable", "mirror", "allyanim"])],
        ["courtchange", new Set(["mirror"])],
        ["decorate", new Set(["allyanim"])],
        ["dragondarts", new Set(["protect", "mirror", "noparentalbond"])],
        ["dragonenergy", new Set(["protect", "mirror"])],
        ["drumbeating", new Set(["protect", "mirror"])],
        ["dualwingbeat", new Set(["contact", "protect", "mirror"])],
        ["dynamaxcannon", new Set(["protect", "failencore", "nosleeptalk", "noparentalbond", "failcopycat", "failinstruct", "failmimic"])],
        ["eeriespell", new Set(["protect", "mirror", "sound", "bypasssub"])],
        ["eternabeam", new Set(["recharge", "protect", "mirror"])],
        ["expandingforce", new Set(["protect", "mirror"])],
        ["falsesurrender", new Set(["contact", "protect", "mirror"])],
        ["fierywrath", new Set(["protect", "mirror"])],
        ["fishiousrend", new Set(["bite", "contact", "protect", "mirror"])],
        ["flipturn", new Set(["contact", "protect", "mirror"])],
        ["freezingglare", new Set(["protect", "mirror"])],
        ["glaciallance", new Set(["protect", "mirror"])],
        ["gmaxbefuddle", new Set([])],
        ["gmaxcannonade", new Set([])],
        ["gmaxcentiferno", new Set([])],
        ["gmaxchistrike", new Set([])],
        ["gmaxcuddle", new Set([])],
        ["gmaxdepletion", new Set([])],
        ["gmaxdrumsolo", new Set([])],
        ["gmaxfinale", new Set([])],
        ["gmaxfireball", new Set([])],
        ["gmaxfoamburst", new Set([])],
        ["gmaxgoldrush", new Set([])],
        ["gmaxgravitas", new Set([])],
        ["gmaxhydrosnipe", new Set([])],
        ["gmaxmalodor", new Set([])],
        ["gmaxmeltdown", new Set([])],
        ["gmaxoneblow", new Set([])],
        ["gmaxrapidflow", new Set([])],
        ["gmaxreplenish", new Set([])],
        ["gmaxresonance", new Set([])],
        ["gmaxsandblast", new Set([])],
        ["gmaxsmite", new Set([])],
        ["gmaxsnooze", new Set([])],
        ["gmaxsteelsurge", new Set([])],
        ["gmaxstonesurge", new Set([])],
        ["gmaxstunshock", new Set([])],
        ["gmaxsweetness", new Set([])],
        ["gmaxtartness", new Set([])],
        ["gmaxterror", new Set([])],
        ["gmaxvinelash", new Set([])],
        ["gmaxvolcalith", new Set([])],
        ["gmaxvoltcrash", new Set([])],
        ["gmaxwildfire", new Set([])],
        ["gmaxwindrage", new Set([])],
        ["grassyglide", new Set(["contact", "protect", "mirror"])],
        ["gravapple", new Set(["protect", "mirror"])],
        ["howl", new Set(["snatch", "sound"])],
        ["jawlock", new Set(["bite", "contact", "protect", "mirror"])],
        ["junglehealing", new Set(["heal", "bypasssub", "allyanim"])],
        ["lashout", new Set(["contact", "protect", "mirror"])],
        ["lifedew", new Set(["snatch", "heal", "bypasssub"])],
        ["magicpowder", new Set(["powder", "protect", "reflectable", "mirror", "allyanim"])],
        ["maxairstream", new Set([])],
        ["maxdarkness", new Set([])],
        ["maxflare", new Set([])],
        ["maxflutterby", new Set([])],
        ["maxgeyser", new Set([])],
        ["maxguard", new Set([])],
        ["maxhailstorm", new Set([])],
        ["maxknuckle", new Set([])],
        ["maxlightning", new Set([])],
        ["maxmindstorm", new Set([])],
        ["maxooze", new Set([])],
        ["maxovergrowth", new Set([])],
        ["maxphantasm", new Set([])],
        ["maxquake", new Set([])],
        ["maxrockfall", new Set([])],
        ["maxstarfall", new Set([])],
        ["maxsteelspike", new Set([])],
        ["maxstrike", new Set([])],
        ["maxwyrmwind", new Set([])],
        ["meteorassault", new Set(["protect", "recharge", "mirror", "failinstruct"])],
        ["meteorbeam", new Set(["charge", "protect", "mirror"])],
        ["mistyexplosion", new Set(["protect", "mirror"])],
        ["noretreat", new Set(["snatch"])],
        ["obstruct", new Set(["failinstruct"])],
        ["octolock", new Set(["protect", "mirror"])],
        ["overdrive", new Set(["protect", "mirror", "sound", "bypasssub"])],
        ["poltergeist", new Set(["protect", "mirror"])],
        ["pyroball", new Set(["protect", "mirror", "defrost", "bullet"])],
        ["risingvoltage", new Set(["protect", "mirror"])],
        ["scaleshot", new Set(["protect", "mirror"])],
        ["scorchingsands", new Set(["protect", "mirror", "defrost"])],
        ["shellsidearm", new Set(["protect", "mirror"])],
        ["skittersmack", new Set(["contact", "protect", "mirror"])],
        ["snaptrap", new Set(["contact", "protect", "mirror"])],
        ["snipeshot", new Set(["protect", "mirror"])],
        ["spiritbreak", new Set(["contact", "protect", "mirror"])],
        ["steelbeam", new Set(["protect", "mirror"])],
        ["steelroller", new Set(["contact", "protect", "mirror"])],
        ["strangesteam", new Set(["protect", "mirror"])],
        ["stuffcheeks", new Set(["snatch"])],
        ["surgingstrikes", new Set(["contact", "protect", "punch", "mirror"])],
        ["tarshot", new Set(["protect", "reflectable", "mirror"])],
        ["teatime", new Set(["bypasssub"])],
        ["terrainpulse", new Set(["protect", "mirror", "pulse"])],
        ["thundercage", new Set(["protect", "mirror"])],
        ["thunderouskick", new Set(["contact", "protect", "mirror"])],
        ["tripleaxel", new Set(["contact", "protect", "mirror"])],
        ["wickedblow", new Set(["contact", "protect", "punch", "mirror"])],
    ])],
    [9, new Map([
        ["aquacutter", new Set(["protect", "mirror", "slicing"])],
        ["aquastep", new Set(["contact", "protect", "mirror", "dance"])],
        ["armorcannon", new Set(["protect", "mirror"])],
        ["axekick", new Set(["contact", "protect", "mirror"])],
        ["barbbarrage", new Set(["protect", "mirror"])],
        ["bitterblade", new Set(["contact", "protect", "mirror", "slicing"])],
        ["bittermalice", new Set(["protect", "mirror"])],
        ["blazingtorque", new Set(["protect", "failencore", "failmefirst", "nosleeptalk", "noassist", "failcopycat", "failinstruct", "failmimic"])],
        ["bleakwindstorm", new Set(["protect", "mirror", "wind"])],
        ["ceaselessedge", new Set(["contact", "protect", "mirror", "slicing"])],
        ["chillingwater", new Set(["protect", "mirror"])],
        ["chillyreception", new Set([])],
        ["chloroblast", new Set(["protect", "mirror"])],
        ["collisioncourse", new Set(["contact", "protect", "mirror"])],
        ["combattorque", new Set(["protect", "failencore", "failmefirst", "nosleeptalk", "noassist", "failcopycat", "failinstruct", "failmimic"])],
        ["comeuppance", new Set(["contact", "protect", "mirror", "failmefirst"])],
        ["direclaw", new Set(["contact", "protect", "mirror"])],
        ["doodle", new Set([])],
        ["doubleshock", new Set(["contact", "protect", "mirror"])],
        ["electrodrift", new Set(["contact", "protect", "mirror"])],
        ["esperwing", new Set(["protect", "mirror"])],
        ["filletaway", new Set(["snatch"])],
        ["flowertrick", new Set(["protect", "mirror"])],
        ["gigatonhammer", new Set(["protect", "mirror", "cantusetwice"])],
        ["glaiverush", new Set(["contact", "protect", "mirror"])],
        ["headlongrush", new Set(["contact", "protect", "mirror", "punch"])],
        ["hydrosteam", new Set(["protect", "mirror", "defrost"])],
        ["hyperdrill", new Set(["contact", "mirror"])],
        ["icespinner", new Set(["contact", "protect", "mirror"])],
        ["infernalparade", new Set(["protect", "mirror"])],
        ["jetpunch", new Set(["contact", "protect", "mirror", "punch"])],
        ["kowtowcleave", new Set(["contact", "protect", "mirror", "slicing"])],
        ["lastrespects", new Set(["protect", "mirror"])],
        ["luminacrash", new Set(["protect", "mirror"])],
        ["lunarblessing", new Set(["snatch", "heal"])],
        ["magicaltorque", new Set(["protect", "failencore", "failmefirst", "nosleeptalk", "noassist", "failcopycat", "failinstruct", "failmimic"])],
        ["makeitrain", new Set(["protect", "mirror"])],
        ["mortalspin", new Set(["contact", "protect", "mirror"])],
        ["mountaingale", new Set(["protect", "mirror"])],
        ["mysticalpower", new Set(["protect", "mirror"])],
        ["noxioustorque", new Set(["protect", "failencore", "failmefirst", "nosleeptalk", "noassist", "failcopycat", "failinstruct", "failmimic"])],
        ["orderup", new Set(["protect"])],
        ["paleowave", new Set(["protect", "mirror"])],
        ["populationbomb", new Set(["contact", "protect", "mirror", "slicing"])],
        ["pounce", new Set(["contact", "protect", "mirror"])],
        ["powershift", new Set(["snatch"])],
        ["psyblade", new Set(["contact", "protect", "mirror", "slicing"])],
        ["psyshieldbash", new Set(["contact", "protect", "mirror"])],
        ["ragefist", new Set(["contact", "protect", "mirror", "punch"])],
        ["ragingbull", new Set(["contact", "protect", "mirror"])],
        ["ragingfury", new Set(["protect", "mirror"])],
        ["revivalblessing", new Set([])],
        ["ruination", new Set(["protect", "mirror"])],
        ["saltcure", new Set(["protect", "mirror"])],
        ["sandsearstorm", new Set(["protect", "mirror", "wind"])],
        ["shadowstrike", new Set(["contact", "protect", "mirror"])],
        ["shedtail", new Set([])],
        ["shelter", new Set(["snatch"])],
        ["silktrap", new Set([])],
        ["snowscape", new Set([])],
        ["spicyextract", new Set(["protect", "reflectable", "mirror"])],
        ["spinout", new Set(["contact", "protect", "mirror"])],
        ["springtidestorm", new Set(["protect", "mirror", "wind"])],
        ["stoneaxe", new Set(["contact", "protect", "mirror", "slicing"])],
        ["takeheart", new Set(["snatch"])],
        ["terablast", new Set(["protect", "mirror", "mustpressure"])],
        ["tidyup", new Set([])],
        ["torchsong", new Set(["protect", "mirror", "sound", "bypasssub"])],
        ["trailblaze", new Set(["contact", "protect", "mirror"])],
        ["triplearrows", new Set(["protect", "mirror"])],
        ["tripledive", new Set(["contact", "protect", "mirror"])],
        ["twinbeam", new Set(["protect", "mirror"])],
        ["victorydance", new Set(["snatch", "dance"])],
        ["wavecrash", new Set(["contact", "protect", "mirror"])],
        ["wickedtorque", new Set(["protect", "failencore", "failmefirst", "nosleeptalk", "noassist", "failcopycat", "failinstruct", "failmimic"])],
        ["wildboltstorm", new Set(["protect", "mirror", "wind"])],
        ["bloodmoon", new Set(["protect", "mirror", "cantusetwice"])],
        ["ivycudgel", new Set(["protect", "mirror"])],
        ["matchagotcha", new Set(["protect", "mirror", "defrost"])],
        ["syrupbomb", new Set(["protect", "mirror", "bullet"])],
    ])],
]);

