// Pokemon types

"use strict";

import { toId } from "../utils/id";

/**
 * Existing pokemon types
 */
export const PokemonTypes = {
    Bug: toId("Bug"),
    Dark: toId("Dark"),
    Dragon: toId("Dragon"),
    Electric: toId("Electric"),
    Fairy: toId("Fairy"),
    Fighting: toId("Fighting"),
    Fire: toId("Fire"),
    Flying: toId("Flying"),
    Ghost: toId("Ghost"),
    Grass: toId("Grass"),
    Ground: toId("Ground"),
    Ice: toId("Ice"),
    Normal: toId("Normal"),
    Poison: toId("Poison"),
    Psychic: toId("Psychic"),
    Rock: toId("Rock"),
    Steel: toId("Steel"),
    Water: toId("Water"),
    Unknown: toId("???"),
};

/**
 * Pokemon type names by ID
 */
export const PokemonTypeNames = new Map<string, string>([
    [PokemonTypes.Bug, "Bug"],
    [PokemonTypes.Dark, "Dark"],
    [PokemonTypes.Dragon, "Dragon"],
    [PokemonTypes.Electric, "Electric"],
    [PokemonTypes.Fairy, "Fairy"],
    [PokemonTypes.Fighting, "Fighting"],
    [PokemonTypes.Fire, "Fire"],
    [PokemonTypes.Flying, "Flying"],
    [PokemonTypes.Ghost, "Ghost"],
    [PokemonTypes.Grass, "Grass"],
    [PokemonTypes.Ground, "Ground"],
    [PokemonTypes.Ice, "Ice"],
    [PokemonTypes.Normal, "Normal"],
    [PokemonTypes.Poison, "Poison"],
    [PokemonTypes.Psychic, "Psychic"],
    [PokemonTypes.Rock, "Rock"],
    [PokemonTypes.Steel, "Steel"],
    [PokemonTypes.Water, "Water"],
    [PokemonTypes.Unknown, "???"],
]);

/**
 * Type chart map (type, type) => multiplier
 */
export type TypeChart = Map<string, Map<string, number>>;

export const EffectiveMul = 1;
export const SuperEffectiveMul = 2;
export const ResistedMul = 0.5;
export const ImmuneMul = 0;

function invertEffectiveness(effectiveness: number): number {
    if (!effectiveness) {
        return 2;
    }
    return 1 / effectiveness;
}

/**
 * Gets effectiveness
 * @param chart The type chart
 * @param offensiveType The offensive type
 * @param defensiveType The defensive type
 * @param isInverse True if inverse battle
 * @returns The multiplier
 */
export function getEffectivenessMultiplier(chart: TypeChart, offensiveType: string, defensiveType: string, isInverse?: boolean): number {
    offensiveType = toId(offensiveType);
    defensiveType = toId(defensiveType);
    if (!chart.has(defensiveType)) {
        return EffectiveMul;
    }
    const subChart = chart.get(defensiveType);
    if (!subChart.has(offensiveType)) {
        return EffectiveMul;
    }

    if (isInverse) {
        return invertEffectiveness(subChart.get(offensiveType));
    }

    return subChart.get(offensiveType);
}

/**
 * Gets effectiveness (combined)
 * @param chart The type chart
 * @param offensiveTypes List of offensive types
 * @param defensiveTypes List of defensive types
 * @param isInverse True if inverse battle
 * @returns The multiplier
 */
export function getCombinedEffectivenessMultiplier(chart: TypeChart, offensiveTypes: string[], defensiveTypes: string[], isInverse?: boolean): number {
    let mul = 1;

    for (const dt of defensiveTypes) {
        for (const ot of offensiveTypes) {
            mul *= getEffectivenessMultiplier(chart, ot, dt, isInverse);
        }
    }

    return mul;
}


/**
 * Type chart from gen 6 to gen 9
 */
export const TypeChartGen6To9: TypeChart = new Map([
    [PokemonTypes.Bug, new Map([
        [PokemonTypes.Bug, EffectiveMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, ResistedMul],
        [PokemonTypes.Fire, SuperEffectiveMul],
        [PokemonTypes.Flying, SuperEffectiveMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, ResistedMul],
        [PokemonTypes.Ground, ResistedMul],
        [PokemonTypes.Ice, EffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, EffectiveMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, SuperEffectiveMul],
        [PokemonTypes.Steel, EffectiveMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Dark, new Map([
        [PokemonTypes.Bug, SuperEffectiveMul],
        [PokemonTypes.Dark, ResistedMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, SuperEffectiveMul],
        [PokemonTypes.Fighting, SuperEffectiveMul],
        [PokemonTypes.Fire, EffectiveMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, ResistedMul],
        [PokemonTypes.Grass, EffectiveMul],
        [PokemonTypes.Ground, EffectiveMul],
        [PokemonTypes.Ice, EffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, EffectiveMul],
        [PokemonTypes.Psychic, ImmuneMul],
        [PokemonTypes.Rock, EffectiveMul],
        [PokemonTypes.Steel, EffectiveMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Dragon, new Map([
        [PokemonTypes.Bug, EffectiveMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, SuperEffectiveMul],
        [PokemonTypes.Electric, ResistedMul],
        [PokemonTypes.Fairy, SuperEffectiveMul],
        [PokemonTypes.Fighting, EffectiveMul],
        [PokemonTypes.Fire, ResistedMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, ResistedMul],
        [PokemonTypes.Ground, EffectiveMul],
        [PokemonTypes.Ice, SuperEffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, EffectiveMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, EffectiveMul],
        [PokemonTypes.Steel, EffectiveMul],
        [PokemonTypes.Water, ResistedMul],
    ])],
    [PokemonTypes.Electric, new Map([
        [PokemonTypes.Bug, EffectiveMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, ResistedMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, EffectiveMul],
        [PokemonTypes.Fire, EffectiveMul],
        [PokemonTypes.Flying, ResistedMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, EffectiveMul],
        [PokemonTypes.Ground, SuperEffectiveMul],
        [PokemonTypes.Ice, EffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, EffectiveMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, EffectiveMul],
        [PokemonTypes.Steel, ResistedMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Fairy, new Map([
        [PokemonTypes.Bug, ResistedMul],
        [PokemonTypes.Dark, ResistedMul],
        [PokemonTypes.Dragon, ImmuneMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, ResistedMul],
        [PokemonTypes.Fire, EffectiveMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, EffectiveMul],
        [PokemonTypes.Ground, EffectiveMul],
        [PokemonTypes.Ice, EffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, SuperEffectiveMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, EffectiveMul],
        [PokemonTypes.Steel, SuperEffectiveMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Fighting, new Map([
        [PokemonTypes.Bug, ResistedMul],
        [PokemonTypes.Dark, ResistedMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, SuperEffectiveMul],
        [PokemonTypes.Fighting, EffectiveMul],
        [PokemonTypes.Fire, EffectiveMul],
        [PokemonTypes.Flying, SuperEffectiveMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, EffectiveMul],
        [PokemonTypes.Ground, EffectiveMul],
        [PokemonTypes.Ice, EffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, EffectiveMul],
        [PokemonTypes.Psychic, SuperEffectiveMul],
        [PokemonTypes.Rock, ResistedMul],
        [PokemonTypes.Steel, EffectiveMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Fire, new Map([
        [PokemonTypes.Bug, ResistedMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, ResistedMul],
        [PokemonTypes.Fighting, EffectiveMul],
        [PokemonTypes.Fire, ResistedMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, ResistedMul],
        [PokemonTypes.Ground, SuperEffectiveMul],
        [PokemonTypes.Ice, ResistedMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, EffectiveMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, SuperEffectiveMul],
        [PokemonTypes.Steel, ResistedMul],
        [PokemonTypes.Water, SuperEffectiveMul],
    ])],
    [PokemonTypes.Flying, new Map([
        [PokemonTypes.Bug, ResistedMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, SuperEffectiveMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, ResistedMul],
        [PokemonTypes.Fire, EffectiveMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, ResistedMul],
        [PokemonTypes.Ground, ImmuneMul],
        [PokemonTypes.Ice, SuperEffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, EffectiveMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, SuperEffectiveMul],
        [PokemonTypes.Steel, EffectiveMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Ghost, new Map([
        [PokemonTypes.Bug, ResistedMul],
        [PokemonTypes.Dark, SuperEffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, ImmuneMul],
        [PokemonTypes.Fire, EffectiveMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, SuperEffectiveMul],
        [PokemonTypes.Grass, EffectiveMul],
        [PokemonTypes.Ground, EffectiveMul],
        [PokemonTypes.Ice, EffectiveMul],
        [PokemonTypes.Normal, ImmuneMul],
        [PokemonTypes.Poison, ResistedMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, EffectiveMul],
        [PokemonTypes.Steel, EffectiveMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Grass, new Map([
        [PokemonTypes.Bug, SuperEffectiveMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, ResistedMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, EffectiveMul],
        [PokemonTypes.Fire, SuperEffectiveMul],
        [PokemonTypes.Flying, SuperEffectiveMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, ResistedMul],
        [PokemonTypes.Ground, ResistedMul],
        [PokemonTypes.Ice, SuperEffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, SuperEffectiveMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, EffectiveMul],
        [PokemonTypes.Steel, EffectiveMul],
        [PokemonTypes.Water, ResistedMul],
    ])],
    [PokemonTypes.Ground, new Map([
        [PokemonTypes.Bug, EffectiveMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, ImmuneMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, EffectiveMul],
        [PokemonTypes.Fire, EffectiveMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, SuperEffectiveMul],
        [PokemonTypes.Ground, EffectiveMul],
        [PokemonTypes.Ice, SuperEffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, ResistedMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, ResistedMul],
        [PokemonTypes.Steel, EffectiveMul],
        [PokemonTypes.Water, SuperEffectiveMul],
    ])],
    [PokemonTypes.Ice, new Map([
        [PokemonTypes.Bug, EffectiveMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, SuperEffectiveMul],
        [PokemonTypes.Fire, SuperEffectiveMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, EffectiveMul],
        [PokemonTypes.Ground, EffectiveMul],
        [PokemonTypes.Ice, ResistedMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, EffectiveMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, SuperEffectiveMul],
        [PokemonTypes.Steel, SuperEffectiveMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Normal, new Map([
        [PokemonTypes.Bug, EffectiveMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, SuperEffectiveMul],
        [PokemonTypes.Fire, EffectiveMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, ImmuneMul],
        [PokemonTypes.Grass, EffectiveMul],
        [PokemonTypes.Ground, EffectiveMul],
        [PokemonTypes.Ice, EffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, EffectiveMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, EffectiveMul],
        [PokemonTypes.Steel, EffectiveMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Poison, new Map([
        [PokemonTypes.Bug, ResistedMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, ResistedMul],
        [PokemonTypes.Fighting, ResistedMul],
        [PokemonTypes.Fire, EffectiveMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, ResistedMul],
        [PokemonTypes.Ground, SuperEffectiveMul],
        [PokemonTypes.Ice, EffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, ResistedMul],
        [PokemonTypes.Psychic, SuperEffectiveMul],
        [PokemonTypes.Rock, EffectiveMul],
        [PokemonTypes.Steel, EffectiveMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Psychic, new Map([
        [PokemonTypes.Bug, SuperEffectiveMul],
        [PokemonTypes.Dark, SuperEffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, ResistedMul],
        [PokemonTypes.Fire, EffectiveMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, SuperEffectiveMul],
        [PokemonTypes.Grass, EffectiveMul],
        [PokemonTypes.Ground, EffectiveMul],
        [PokemonTypes.Ice, EffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, EffectiveMul],
        [PokemonTypes.Psychic, ResistedMul],
        [PokemonTypes.Rock, EffectiveMul],
        [PokemonTypes.Steel, EffectiveMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Rock, new Map([
        [PokemonTypes.Bug, EffectiveMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, SuperEffectiveMul],
        [PokemonTypes.Fire, ResistedMul],
        [PokemonTypes.Flying, ResistedMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, SuperEffectiveMul],
        [PokemonTypes.Ground, SuperEffectiveMul],
        [PokemonTypes.Ice, EffectiveMul],
        [PokemonTypes.Normal, ResistedMul],
        [PokemonTypes.Poison, ResistedMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, EffectiveMul],
        [PokemonTypes.Steel, SuperEffectiveMul],
        [PokemonTypes.Water, SuperEffectiveMul],
    ])],
    [PokemonTypes.Steel, new Map([
        [PokemonTypes.Bug, ResistedMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, ResistedMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, ResistedMul],
        [PokemonTypes.Fighting, SuperEffectiveMul],
        [PokemonTypes.Fire, SuperEffectiveMul],
        [PokemonTypes.Flying, ResistedMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, ResistedMul],
        [PokemonTypes.Ground, SuperEffectiveMul],
        [PokemonTypes.Ice, ResistedMul],
        [PokemonTypes.Normal, ResistedMul],
        [PokemonTypes.Poison, ImmuneMul],
        [PokemonTypes.Psychic, ResistedMul],
        [PokemonTypes.Rock, ResistedMul],
        [PokemonTypes.Steel, ResistedMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Water, new Map([
        [PokemonTypes.Bug, EffectiveMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, SuperEffectiveMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, EffectiveMul],
        [PokemonTypes.Fire, ResistedMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, SuperEffectiveMul],
        [PokemonTypes.Ground, EffectiveMul],
        [PokemonTypes.Ice, ResistedMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, EffectiveMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, EffectiveMul],
        [PokemonTypes.Steel, ResistedMul],
        [PokemonTypes.Water, ResistedMul],
    ])],
]);

/**
 * Type chart from gen 2 to gen 5
 */
export const TypeChartGen2ToGen5 = new Map([
    [PokemonTypes.Bug, new Map([
        [PokemonTypes.Bug, EffectiveMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, ResistedMul],
        [PokemonTypes.Fire, SuperEffectiveMul],
        [PokemonTypes.Flying, SuperEffectiveMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, ResistedMul],
        [PokemonTypes.Ground, ResistedMul],
        [PokemonTypes.Ice, EffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, EffectiveMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, SuperEffectiveMul],
        [PokemonTypes.Steel, EffectiveMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Dark, new Map([
        [PokemonTypes.Bug, SuperEffectiveMul],
        [PokemonTypes.Dark, ResistedMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, SuperEffectiveMul],
        [PokemonTypes.Fighting, SuperEffectiveMul],
        [PokemonTypes.Fire, EffectiveMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, ResistedMul],
        [PokemonTypes.Grass, EffectiveMul],
        [PokemonTypes.Ground, EffectiveMul],
        [PokemonTypes.Ice, EffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, EffectiveMul],
        [PokemonTypes.Psychic, ImmuneMul],
        [PokemonTypes.Rock, EffectiveMul],
        [PokemonTypes.Steel, EffectiveMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Dragon, new Map([
        [PokemonTypes.Bug, EffectiveMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, SuperEffectiveMul],
        [PokemonTypes.Electric, ResistedMul],
        [PokemonTypes.Fairy, SuperEffectiveMul],
        [PokemonTypes.Fighting, EffectiveMul],
        [PokemonTypes.Fire, ResistedMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, ResistedMul],
        [PokemonTypes.Ground, EffectiveMul],
        [PokemonTypes.Ice, SuperEffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, EffectiveMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, EffectiveMul],
        [PokemonTypes.Steel, EffectiveMul],
        [PokemonTypes.Water, ResistedMul],
    ])],
    [PokemonTypes.Electric, new Map([
        [PokemonTypes.Bug, EffectiveMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, ResistedMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, EffectiveMul],
        [PokemonTypes.Fire, EffectiveMul],
        [PokemonTypes.Flying, ResistedMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, EffectiveMul],
        [PokemonTypes.Ground, SuperEffectiveMul],
        [PokemonTypes.Ice, EffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, EffectiveMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, EffectiveMul],
        [PokemonTypes.Steel, ResistedMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Fairy, new Map([
        [PokemonTypes.Bug, ResistedMul],
        [PokemonTypes.Dark, ResistedMul],
        [PokemonTypes.Dragon, ImmuneMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, ResistedMul],
        [PokemonTypes.Fire, EffectiveMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, EffectiveMul],
        [PokemonTypes.Ground, EffectiveMul],
        [PokemonTypes.Ice, EffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, SuperEffectiveMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, EffectiveMul],
        [PokemonTypes.Steel, SuperEffectiveMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Fighting, new Map([
        [PokemonTypes.Bug, ResistedMul],
        [PokemonTypes.Dark, ResistedMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, SuperEffectiveMul],
        [PokemonTypes.Fighting, EffectiveMul],
        [PokemonTypes.Fire, EffectiveMul],
        [PokemonTypes.Flying, SuperEffectiveMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, EffectiveMul],
        [PokemonTypes.Ground, EffectiveMul],
        [PokemonTypes.Ice, EffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, EffectiveMul],
        [PokemonTypes.Psychic, SuperEffectiveMul],
        [PokemonTypes.Rock, ResistedMul],
        [PokemonTypes.Steel, EffectiveMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Fire, new Map([
        [PokemonTypes.Bug, ResistedMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, ResistedMul],
        [PokemonTypes.Fighting, EffectiveMul],
        [PokemonTypes.Fire, ResistedMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, ResistedMul],
        [PokemonTypes.Ground, SuperEffectiveMul],
        [PokemonTypes.Ice, ResistedMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, EffectiveMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, SuperEffectiveMul],
        [PokemonTypes.Steel, ResistedMul],
        [PokemonTypes.Water, SuperEffectiveMul],
    ])],
    [PokemonTypes.Flying, new Map([
        [PokemonTypes.Bug, ResistedMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, SuperEffectiveMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, ResistedMul],
        [PokemonTypes.Fire, EffectiveMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, ResistedMul],
        [PokemonTypes.Ground, ImmuneMul],
        [PokemonTypes.Ice, SuperEffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, EffectiveMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, SuperEffectiveMul],
        [PokemonTypes.Steel, EffectiveMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Ghost, new Map([
        [PokemonTypes.Bug, ResistedMul],
        [PokemonTypes.Dark, SuperEffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, ImmuneMul],
        [PokemonTypes.Fire, EffectiveMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, SuperEffectiveMul],
        [PokemonTypes.Grass, EffectiveMul],
        [PokemonTypes.Ground, EffectiveMul],
        [PokemonTypes.Ice, EffectiveMul],
        [PokemonTypes.Normal, ImmuneMul],
        [PokemonTypes.Poison, ResistedMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, EffectiveMul],
        [PokemonTypes.Steel, EffectiveMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Grass, new Map([
        [PokemonTypes.Bug, SuperEffectiveMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, ResistedMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, EffectiveMul],
        [PokemonTypes.Fire, SuperEffectiveMul],
        [PokemonTypes.Flying, SuperEffectiveMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, ResistedMul],
        [PokemonTypes.Ground, ResistedMul],
        [PokemonTypes.Ice, SuperEffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, SuperEffectiveMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, EffectiveMul],
        [PokemonTypes.Steel, EffectiveMul],
        [PokemonTypes.Water, ResistedMul],
    ])],
    [PokemonTypes.Ground, new Map([
        [PokemonTypes.Bug, EffectiveMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, ImmuneMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, EffectiveMul],
        [PokemonTypes.Fire, EffectiveMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, SuperEffectiveMul],
        [PokemonTypes.Ground, EffectiveMul],
        [PokemonTypes.Ice, SuperEffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, ResistedMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, ResistedMul],
        [PokemonTypes.Steel, EffectiveMul],
        [PokemonTypes.Water, SuperEffectiveMul],
    ])],
    [PokemonTypes.Ice, new Map([
        [PokemonTypes.Bug, EffectiveMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, SuperEffectiveMul],
        [PokemonTypes.Fire, SuperEffectiveMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, EffectiveMul],
        [PokemonTypes.Ground, EffectiveMul],
        [PokemonTypes.Ice, ResistedMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, EffectiveMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, SuperEffectiveMul],
        [PokemonTypes.Steel, SuperEffectiveMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Normal, new Map([
        [PokemonTypes.Bug, EffectiveMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, SuperEffectiveMul],
        [PokemonTypes.Fire, EffectiveMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, ImmuneMul],
        [PokemonTypes.Grass, EffectiveMul],
        [PokemonTypes.Ground, EffectiveMul],
        [PokemonTypes.Ice, EffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, EffectiveMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, EffectiveMul],
        [PokemonTypes.Steel, EffectiveMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Poison, new Map([
        [PokemonTypes.Bug, ResistedMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, ResistedMul],
        [PokemonTypes.Fighting, ResistedMul],
        [PokemonTypes.Fire, EffectiveMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, ResistedMul],
        [PokemonTypes.Ground, SuperEffectiveMul],
        [PokemonTypes.Ice, EffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, ResistedMul],
        [PokemonTypes.Psychic, SuperEffectiveMul],
        [PokemonTypes.Rock, EffectiveMul],
        [PokemonTypes.Steel, EffectiveMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Psychic, new Map([
        [PokemonTypes.Bug, SuperEffectiveMul],
        [PokemonTypes.Dark, SuperEffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, ResistedMul],
        [PokemonTypes.Fire, EffectiveMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, SuperEffectiveMul],
        [PokemonTypes.Grass, EffectiveMul],
        [PokemonTypes.Ground, EffectiveMul],
        [PokemonTypes.Ice, EffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, EffectiveMul],
        [PokemonTypes.Psychic, ResistedMul],
        [PokemonTypes.Rock, EffectiveMul],
        [PokemonTypes.Steel, EffectiveMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Rock, new Map([
        [PokemonTypes.Bug, EffectiveMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, SuperEffectiveMul],
        [PokemonTypes.Fire, ResistedMul],
        [PokemonTypes.Flying, ResistedMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, SuperEffectiveMul],
        [PokemonTypes.Ground, SuperEffectiveMul],
        [PokemonTypes.Ice, EffectiveMul],
        [PokemonTypes.Normal, ResistedMul],
        [PokemonTypes.Poison, ResistedMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, EffectiveMul],
        [PokemonTypes.Steel, SuperEffectiveMul],
        [PokemonTypes.Water, SuperEffectiveMul],
    ])],
    [PokemonTypes.Steel, new Map([
        [PokemonTypes.Bug, ResistedMul],
        [PokemonTypes.Dark, ResistedMul],
        [PokemonTypes.Dragon, ResistedMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, ResistedMul],
        [PokemonTypes.Fighting, SuperEffectiveMul],
        [PokemonTypes.Fire, SuperEffectiveMul],
        [PokemonTypes.Flying, ResistedMul],
        [PokemonTypes.Ghost, ResistedMul],
        [PokemonTypes.Grass, ResistedMul],
        [PokemonTypes.Ground, SuperEffectiveMul],
        [PokemonTypes.Ice, ResistedMul],
        [PokemonTypes.Normal, ResistedMul],
        [PokemonTypes.Poison, ImmuneMul],
        [PokemonTypes.Psychic, ResistedMul],
        [PokemonTypes.Rock, ResistedMul],
        [PokemonTypes.Steel, ResistedMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Water, new Map([
        [PokemonTypes.Bug, EffectiveMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, SuperEffectiveMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, EffectiveMul],
        [PokemonTypes.Fire, ResistedMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, SuperEffectiveMul],
        [PokemonTypes.Ground, EffectiveMul],
        [PokemonTypes.Ice, ResistedMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, EffectiveMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, EffectiveMul],
        [PokemonTypes.Steel, ResistedMul],
        [PokemonTypes.Water, ResistedMul],
    ])],
]);

export const TypeChartGen1 = new Map([
    [PokemonTypes.Bug, new Map([
        [PokemonTypes.Bug, EffectiveMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, ResistedMul],
        [PokemonTypes.Fire, SuperEffectiveMul],
        [PokemonTypes.Flying, SuperEffectiveMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, ResistedMul],
        [PokemonTypes.Ground, ResistedMul],
        [PokemonTypes.Ice, EffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, EffectiveMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, SuperEffectiveMul],
        [PokemonTypes.Steel, EffectiveMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Dark, new Map([
        [PokemonTypes.Bug, SuperEffectiveMul],
        [PokemonTypes.Dark, ResistedMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, SuperEffectiveMul],
        [PokemonTypes.Fighting, SuperEffectiveMul],
        [PokemonTypes.Fire, EffectiveMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, ResistedMul],
        [PokemonTypes.Grass, EffectiveMul],
        [PokemonTypes.Ground, EffectiveMul],
        [PokemonTypes.Ice, EffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, EffectiveMul],
        [PokemonTypes.Psychic, ImmuneMul],
        [PokemonTypes.Rock, EffectiveMul],
        [PokemonTypes.Steel, EffectiveMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Dragon, new Map([
        [PokemonTypes.Bug, EffectiveMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, SuperEffectiveMul],
        [PokemonTypes.Electric, ResistedMul],
        [PokemonTypes.Fairy, SuperEffectiveMul],
        [PokemonTypes.Fighting, EffectiveMul],
        [PokemonTypes.Fire, ResistedMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, ResistedMul],
        [PokemonTypes.Ground, EffectiveMul],
        [PokemonTypes.Ice, SuperEffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, EffectiveMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, EffectiveMul],
        [PokemonTypes.Steel, EffectiveMul],
        [PokemonTypes.Water, ResistedMul],
    ])],
    [PokemonTypes.Electric, new Map([
        [PokemonTypes.Bug, EffectiveMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, ResistedMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, EffectiveMul],
        [PokemonTypes.Fire, EffectiveMul],
        [PokemonTypes.Flying, ResistedMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, EffectiveMul],
        [PokemonTypes.Ground, SuperEffectiveMul],
        [PokemonTypes.Ice, EffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, EffectiveMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, EffectiveMul],
        [PokemonTypes.Steel, ResistedMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Fairy, new Map([
        [PokemonTypes.Bug, ResistedMul],
        [PokemonTypes.Dark, ResistedMul],
        [PokemonTypes.Dragon, ImmuneMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, ResistedMul],
        [PokemonTypes.Fire, EffectiveMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, EffectiveMul],
        [PokemonTypes.Ground, EffectiveMul],
        [PokemonTypes.Ice, EffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, SuperEffectiveMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, EffectiveMul],
        [PokemonTypes.Steel, SuperEffectiveMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Fighting, new Map([
        [PokemonTypes.Bug, ResistedMul],
        [PokemonTypes.Dark, ResistedMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, SuperEffectiveMul],
        [PokemonTypes.Fighting, EffectiveMul],
        [PokemonTypes.Fire, EffectiveMul],
        [PokemonTypes.Flying, SuperEffectiveMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, EffectiveMul],
        [PokemonTypes.Ground, EffectiveMul],
        [PokemonTypes.Ice, EffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, EffectiveMul],
        [PokemonTypes.Psychic, SuperEffectiveMul],
        [PokemonTypes.Rock, ResistedMul],
        [PokemonTypes.Steel, EffectiveMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Fire, new Map([
        [PokemonTypes.Bug, ResistedMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, ResistedMul],
        [PokemonTypes.Fighting, EffectiveMul],
        [PokemonTypes.Fire, ResistedMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, ResistedMul],
        [PokemonTypes.Ground, SuperEffectiveMul],
        [PokemonTypes.Ice, ResistedMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, EffectiveMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, SuperEffectiveMul],
        [PokemonTypes.Steel, ResistedMul],
        [PokemonTypes.Water, SuperEffectiveMul],
    ])],
    [PokemonTypes.Flying, new Map([
        [PokemonTypes.Bug, ResistedMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, SuperEffectiveMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, ResistedMul],
        [PokemonTypes.Fire, EffectiveMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, ResistedMul],
        [PokemonTypes.Ground, ImmuneMul],
        [PokemonTypes.Ice, SuperEffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, EffectiveMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, SuperEffectiveMul],
        [PokemonTypes.Steel, EffectiveMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Ghost, new Map([
        [PokemonTypes.Bug, ResistedMul],
        [PokemonTypes.Dark, SuperEffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, ImmuneMul],
        [PokemonTypes.Fire, EffectiveMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, SuperEffectiveMul],
        [PokemonTypes.Grass, EffectiveMul],
        [PokemonTypes.Ground, EffectiveMul],
        [PokemonTypes.Ice, EffectiveMul],
        [PokemonTypes.Normal, ImmuneMul],
        [PokemonTypes.Poison, ResistedMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, EffectiveMul],
        [PokemonTypes.Steel, EffectiveMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Grass, new Map([
        [PokemonTypes.Bug, SuperEffectiveMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, ResistedMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, EffectiveMul],
        [PokemonTypes.Fire, SuperEffectiveMul],
        [PokemonTypes.Flying, SuperEffectiveMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, ResistedMul],
        [PokemonTypes.Ground, ResistedMul],
        [PokemonTypes.Ice, SuperEffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, SuperEffectiveMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, EffectiveMul],
        [PokemonTypes.Steel, EffectiveMul],
        [PokemonTypes.Water, ResistedMul],
    ])],
    [PokemonTypes.Ground, new Map([
        [PokemonTypes.Bug, EffectiveMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, ImmuneMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, EffectiveMul],
        [PokemonTypes.Fire, EffectiveMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, SuperEffectiveMul],
        [PokemonTypes.Ground, EffectiveMul],
        [PokemonTypes.Ice, SuperEffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, ResistedMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, ResistedMul],
        [PokemonTypes.Steel, EffectiveMul],
        [PokemonTypes.Water, SuperEffectiveMul],
    ])],
    [PokemonTypes.Ice, new Map([
        [PokemonTypes.Bug, EffectiveMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, SuperEffectiveMul],
        [PokemonTypes.Fire, SuperEffectiveMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, EffectiveMul],
        [PokemonTypes.Ground, EffectiveMul],
        [PokemonTypes.Ice, ResistedMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, EffectiveMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, SuperEffectiveMul],
        [PokemonTypes.Steel, SuperEffectiveMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Normal, new Map([
        [PokemonTypes.Bug, EffectiveMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, SuperEffectiveMul],
        [PokemonTypes.Fire, EffectiveMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, ImmuneMul],
        [PokemonTypes.Grass, EffectiveMul],
        [PokemonTypes.Ground, EffectiveMul],
        [PokemonTypes.Ice, EffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, EffectiveMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, EffectiveMul],
        [PokemonTypes.Steel, EffectiveMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Poison, new Map([
        [PokemonTypes.Bug, ResistedMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, ResistedMul],
        [PokemonTypes.Fighting, ResistedMul],
        [PokemonTypes.Fire, EffectiveMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, ResistedMul],
        [PokemonTypes.Ground, SuperEffectiveMul],
        [PokemonTypes.Ice, EffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, ResistedMul],
        [PokemonTypes.Psychic, SuperEffectiveMul],
        [PokemonTypes.Rock, EffectiveMul],
        [PokemonTypes.Steel, EffectiveMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Psychic, new Map([
        [PokemonTypes.Bug, SuperEffectiveMul],
        [PokemonTypes.Dark, SuperEffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, ResistedMul],
        [PokemonTypes.Fire, EffectiveMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, ImmuneMul],
        [PokemonTypes.Grass, EffectiveMul],
        [PokemonTypes.Ground, EffectiveMul],
        [PokemonTypes.Ice, EffectiveMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, EffectiveMul],
        [PokemonTypes.Psychic, ResistedMul],
        [PokemonTypes.Rock, EffectiveMul],
        [PokemonTypes.Steel, EffectiveMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Rock, new Map([
        [PokemonTypes.Bug, EffectiveMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, SuperEffectiveMul],
        [PokemonTypes.Fire, ResistedMul],
        [PokemonTypes.Flying, ResistedMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, SuperEffectiveMul],
        [PokemonTypes.Ground, SuperEffectiveMul],
        [PokemonTypes.Ice, EffectiveMul],
        [PokemonTypes.Normal, ResistedMul],
        [PokemonTypes.Poison, ResistedMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, EffectiveMul],
        [PokemonTypes.Steel, SuperEffectiveMul],
        [PokemonTypes.Water, SuperEffectiveMul],
    ])],
    [PokemonTypes.Steel, new Map([
        [PokemonTypes.Bug, ResistedMul],
        [PokemonTypes.Dark, ResistedMul],
        [PokemonTypes.Dragon, ResistedMul],
        [PokemonTypes.Electric, EffectiveMul],
        [PokemonTypes.Fairy, ResistedMul],
        [PokemonTypes.Fighting, SuperEffectiveMul],
        [PokemonTypes.Fire, SuperEffectiveMul],
        [PokemonTypes.Flying, ResistedMul],
        [PokemonTypes.Ghost, ResistedMul],
        [PokemonTypes.Grass, ResistedMul],
        [PokemonTypes.Ground, SuperEffectiveMul],
        [PokemonTypes.Ice, ResistedMul],
        [PokemonTypes.Normal, ResistedMul],
        [PokemonTypes.Poison, ImmuneMul],
        [PokemonTypes.Psychic, ResistedMul],
        [PokemonTypes.Rock, ResistedMul],
        [PokemonTypes.Steel, ResistedMul],
        [PokemonTypes.Water, EffectiveMul],
    ])],
    [PokemonTypes.Water, new Map([
        [PokemonTypes.Bug, EffectiveMul],
        [PokemonTypes.Dark, EffectiveMul],
        [PokemonTypes.Dragon, EffectiveMul],
        [PokemonTypes.Electric, SuperEffectiveMul],
        [PokemonTypes.Fairy, EffectiveMul],
        [PokemonTypes.Fighting, EffectiveMul],
        [PokemonTypes.Fire, ResistedMul],
        [PokemonTypes.Flying, EffectiveMul],
        [PokemonTypes.Ghost, EffectiveMul],
        [PokemonTypes.Grass, SuperEffectiveMul],
        [PokemonTypes.Ground, EffectiveMul],
        [PokemonTypes.Ice, ResistedMul],
        [PokemonTypes.Normal, EffectiveMul],
        [PokemonTypes.Poison, EffectiveMul],
        [PokemonTypes.Psychic, EffectiveMul],
        [PokemonTypes.Rock, EffectiveMul],
        [PokemonTypes.Steel, ResistedMul],
        [PokemonTypes.Water, ResistedMul],
    ])],
]);

/**
 * Gets type chart for generation
 * @param gen The generation
 * @returns The type chart
 */
export function getTypeChart(gen: number): TypeChart {
    if (gen === 1) {
        return TypeChartGen1;
    } else if (gen < 6) {
        return TypeChartGen2ToGen5;
    } else {
        return TypeChartGen6To9;
    }
}
